### ISSUE TITLE
Generated pptx file opened with errorin Office Powerpoint

### ISSUE THREAD

**Issue by Evergreenn** [PHPOffice/PHPPresentation#100]
Hi,
I've got the same problem (https://github.com/PHPOffice/PHPPowerPoint/issues/47) but I have the new version with the 2 patches included.. It don't fix anything for me.

It is only on Microsoft Powerpoint ( i've only tested on 2013 version), it work fine with Openoffice and Libreoffice.

I don't know how to fix it

Thanks for your time !
Evergreenn

**Comment by Progi1984** [comment]
@Evergreenn Have you a code for generated a "corrupted" file ? Because with my 2007 version, I have no problem.

**Comment by rocity** [comment]
I've got the same problem.  Using powerpoint 2007

**Comment by domondon1** [comment]
also me,,im using the 2007 microsoft powerpoint and i got the same pop up
error,please reply

**Comment by Evergreenn** [comment]
Hi, check all your fields, Microsoft Office don't like empty text field. I works for me..

**Comment by rocity** [comment]
ohh i see. i will try your suggestion.

**Comment by rocity** [comment]
@Evergreenn still doesn't work.. im still getting erros when opening the power point

**Comment by Evergreenn** [comment]
Hmm.. maybe a picture not found ?

**Comment by domondon1** [comment]
@Evergreenn what version are you using phppowerpoint?

**Comment by Progi1984** [comment]
@domondon1 @Evergreenn @rocity Could you look at this comment : https://github.com/PHPOffice/PHPPowerPoint/issues/89#issuecomment-112753091 ? And give me some feedback. Thanks :)

**Comment by Progi1984** [comment]
@domondon1 @Evergreenn @rocity PHPPowerPoint 0.4.0 has been released. I would like to solve your issue for 0.5.0. Could you answer to my question ?

**Comment by domondon1** [comment]
i have a question @Progi1984 I open the ppt file on microsoft powerpoint 2007 and its working fine,but when i open the ppt file on microsoft powerpoint 2010,there is a pop up saying "repair"

**Comment by rocity** [comment]
Mine is a bit strange.  working on 2007 after applying what @Evergreenn  has told me it still doesn't fix the repair error in 2013.

**Comment by Progi1984** [comment]
@domondon1 Warning ! You talk about PPT file and not PPTX file.

@domondon1 @rocity Could you validate your files with [OpenXML Validator](http://tech.trailmax.info/2014/04/open-xml-sdk-tool-to-analyse-documents-and-generated-c-code/) ?
You can change the validator format.

![image](https://cloud.githubusercontent.com/assets/1533248/8645368/109e29e4-2947-11e5-80b4-7b1b6b0d47bb.png)

If errors, could you send me your files ?

**Comment by jqr108** [comment]
Hi @Progi1984 @domondon1 @rocity 

Wanted to let you all know I ran into a similar issue. PPTX files needed repair, and but when repaired none of my charts would show up. I managed to fix this by checking out  the XML tool above. The issue I was having was, to paraphrase the XML tool (sorry can't copy from it):

"Invalid child element 'chart:strLit", only "chart:numLit' and 'chart:numRef' supported."

My quick fix was to make sure to intval() or floatval() all data passed to the Chart Series. Looks like the code at issue here is on line /Writer/PowerPoint2007/Chart.php.

Not sure if this is the same issue others are having but I thought I would share!

**Comment by RightHandedMonkey** [comment]
Question: Were you getting this issue intermittently?  

I don't see how this could be the same as my issue because sometimes I'll get the error and but most times I won't.  I'm having issues where the same code being output the majority of the time works, but some times the corrupt file message occurs and I'll have a missing image or a missing slide.

Here is my issue:
https://github.com/PHPOffice/PHPPresentation/issues/132

**Comment by Progi1984** [comment]
@Evergreenn @rocity @domondon1 @jqr108 @RightHandedMonkey Could you test with the latest version of the develop branch (with #89 & PR #167) ?

**Comment by Progi1984** [comment]
@Evergreenn @rocity @domondon1 @jqr108 @RightHandedMonkey PHPPowerPoint 0.6.0 has been released. I would like to solve your issue for 0.7.0. Could you test the last develop version ?

**Comment by Evergreenn** [comment]
@Progi1984 Yes ! All seems to be good for me, thanks a lot !

**Comment by meriemagg** [comment]
@Evergreenn  HI  i have the same issue with powerpoint 2013 could you tell me please how you solved the problem ?

**Comment by Riaz1** [comment]
I am having the same issue, code to recreate error:

require_once 'vendor/autoload.php';

use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Alignment;

$objPHPPowerPoint = new PhpPresentation();

// Create slide
$currentSlide = $objPHPPowerPoint->getActiveSlide();

// Create a shape (text)
$shape = $currentSlide->createRichTextShape()
      ->setHeight(300)
      ->setWidth(600)
      ->setOffsetX(170)
      ->setOffsetY(180);
$shape->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_CENTER );
$textRun = $shape->createTextRun('Thank you for using PHPPresentation!');
$textRun->getFont()->setBold(true)
                   ->setSize(60)
                   ->setColor( new Color( 'FFE06B20' ) );


// Create slide
$currentSlide1 = $objPHPPowerPoint->createSlide();

// Create a shape (text)
$shape1 = $currentSlide1->createRichTextShape()
      ->setHeight(300)
      ->setWidth(600)
      ->setOffsetX(170)
      ->setOffsetY(180);
$shape1->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_CENTER );
$textRun1 = $shape1->createTextRun('Thank you for using PHPPresentation!');
$textRun1->getFont()->setBold(true)
                   ->setSize(60)
                   ->setColor( new Color( 'FFE06B20' ) );

$oWriterODP = IOFactory::createWriter($objPHPPowerPoint, 'ODPresentation');
$oWriterODP->save(__DIR__ . "/t1.odp");


---------------------------------------------------------
The code below does not create an error:

require_once 'vendor/autoload.php';

use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Alignment;

$objPHPPowerPoint = new PhpPresentation();

// Create slide
$currentSlide = $objPHPPowerPoint->getActiveSlide();

// Create a shape (text)
$shape = $currentSlide->createRichTextShape()
      ->setHeight(300)
      ->setWidth(600)
      ->setOffsetX(170)
      ->setOffsetY(180);
$shape->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_CENTER );
$textRun = $shape->createTextRun('Thank you for using PHPPresentation!');
$textRun->getFont()->setBold(true)
                   ->setSize(60)
                   ->setColor( new Color( 'FFE06B20' ) );

$oWriterODP = IOFactory::createWriter($objPHPPowerPoint, 'ODPresentation');
$oWriterODP->save(__DIR__ . "/t1.odp");

------------------------------------------
Microsoft Powerpoint is able to open and repair the 'corrupt' file.

**Comment by Progi1984** [comment]
@Riaz1 You try to create an ODP file, not a PPTX.

**Comment by meriemagg** [comment]
@Progi1984 i created a pptx file and i am getting the same error message when i try to open the pptx fie
can you please check if there's anything wrong whith the way i am generating the slides 
  here is my code 



 $objPHPPowerPoint = new PhpPresentation();
  $j = 0 ;

 foreach ($tab_wil as $key => $value) {

  $sql2 = " SELECT f.id, r.region, w.wilaya, c.commune, a.adresse, t.type, t.dimension_l, t.dimension_h, f.infos, f.code, f.id_wilaya, f.id_commune, f.id_adresse, f.id_type, f.id_region

  			   FROM faces AS f

  			   JOIN regions AS r
  			   ON f.id_region = r.id_region

  			   JOIN wilayas AS w
  			   ON f.id_wilaya = w.id_wilaya

  			   JOIN communes AS c
  			   ON f.id_commune = c.id_commune

  			   JOIN types AS t
  			   ON f.id_type = t.id_type

  			   JOIN adresses AS a
  			   ON f.id_adresse = a.id_adresse


   			   WHERE inactive !='1' AND f.id IN($faces_dispo) AND f.id_wilaya = ".$key."
  			   ORDER BY w.wilaya, c.commune, a.adresse, f.id " ;

            $sth2 = $conn->prepare($sql2);
            $sth2->execute();

// *************      i create a slide containing only text    ***********
 	while ( $aff_listFaces = $sth2-> fetchAll(PDO::FETCH_ASSOC) )
			     {

                  $slide = $objPHPPowerPoint->getActiveSlide();
                  $text = $slide->createRichTextShape()
                      ->setHeight(300)
                      ->setWidth(600)
                      ->setOffsetX(170)
                      ->setOffsetY(180);

                  $textRun = $text->createTextRun( $key );
                 $textRun->getFont()
                       ->setBold(true)
                       ->setSize(30)
                       ->setColor(new Color('FFE06B20'));



             $z = 0 ;

// ***********************  for each slide i loop create several sub slides     *******************

             while(!empty($aff_listFaces[$z]['id'])) {

               $slide = $objPHPPowerPoint->getActiveSlide();
               $text = $slide->createRichTextShape()
                   ->setHeight(300)
                   ->setWidth(600)
                   ->setOffsetX(170)
                   ->setOffsetY(180);

               $textRun = $text->createTextRun($aff_listFaces[$z]['id'] );

            if (file_exists('../gestipub.odvplus.com/data/photos/'.$aff_listFaces[$z]['id_wilaya'].'/'.$aff_listFaces[$z]['id'].'.JPG')) {


                           // the image added to the slide
                           $shape = new Drawing\File();
                           $shape->setName($aff_listFaces[$z]['id'] )
                               ->setDescription('')
                               ->setPath('../gestipub.odvplus.com/data/photos/'.$aff_listFaces[$z]['id_wilaya'].'/'.$aff_listFaces[$z]['id'].'.JPG')

                               ->setWidth(300)
                               ->setHeight(300)
                               ->setOffsetX(50)
                               ->setOffsetY(100);

                           $slide->addShape($shape);

                         }else{

                           // the image added to the slide
                           $shape = new Drawing\File();
                           $shape->setName($aff_listFaces[$z]['id'] )
                               ->setDescription('')
                               ->setPath('../gestipub.odvplus.com/data/photos/default.jpg')

                               ->setWidth(300)
                               ->setHeight(300)
                               ->setOffsetX(50)
                               ->setOffsetY(100);

                           $slide->addShape($shape);

                          }

       $z++ ;

             }
// ***********************  END OF SUB SLIDE LOOP     *******************
	}

 // ***********************  END OF MAIN LOOP     *******************

      $oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');
      $oWriterPPTX->save(__DIR__ . "/results/".$_GET["key"].".pptx");

?>

**Comment by sangramsingh67** [comment]
### Sangram Singh ####
