### ISSUE TITLE
Set name of a slide

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPPresentation#121]
OpenDocument :
* draw:page draw:name="Ma Diapo"

**Comment by haktansuren** [comment]
Hi Progi, Any future fix for PowerPoint2007?

**Comment by Progi1984** [comment]
@haktansuren Could you define the name of a slide in PPT2007 ? Have you a screenshot for this feature in PPT2007 ?

**Comment by haktansuren** [comment]
@Progi1984 
Here is the screen shot you asked. 
![image](https://cloud.githubusercontent.com/assets/17882120/13821053/6a5d7920-eb76-11e5-947b-7e3af0481797.png)

I think, it should be in app.xml 

`<vt:lpstr>Yes this is the slide name…</vt:lpstr>`

**Comment by Progi1984** [comment]
@haktansuren It's not the slide name, it's the content of a placeholder.

**Comment by haktansuren** [comment]
Thanks @Progi1984,

Is it possible to use placeholder with draw object? It means, can i first create placeholder and then place the text in placeholder while generating the PPTX? 

Thanks

**Comment by Progi1984** [comment]
@haktansuren It's in the milestone 0.7 (#161).
