### ISSUE TITLE
Embed a video 

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPPresentation#123]
http://www.aspose.com/docs/display/slidesnet/Adding+an+Embedded+Video+Frame+to+Slide
https://support.office.com/en-us/article/Compatible-multimedia-file-formats-fe6b7fd4-629e-43a0-a7e2-0dd927dac56d

* OpenXML
  * https://msdn.microsoft.com/en-us/library/dd947021(v=office.12).aspx
* OpenDocument
  * http://ask.libreoffice.org/en/question/1898/how-to-embed-video-into-impress-presentation/
  * http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1415866_253892949

```xml
<draw:frame draw:style-name="standard" draw:layer="layout" svg:width="33.866cm" svg:height="19.049cm" svg:x="-2.932cm" svg:y="0.976cm">
	<draw:plugin xlink:href="Media/Wildlife.wmv" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" draw:mime-type="application/vnd.sun.star.media">
		<draw:param draw:name="Loop" draw:value="false"/>
		<draw:param draw:name="Mute" draw:value="false"/>
		<draw:param draw:name="VolumeDB" draw:value="0"/>
		<draw:param draw:name="Zoom" draw:value="fit"/>
	</draw:plugin>
</draw:frame>
```

**Comment by jjmontgo** [comment]
Is anything being done with this issue?

**Comment by Progi1984** [comment]
@jjmontgo For the moment, but we are open to pull requests :)

**Comment by jjmontgo** [comment]
Thank you so much for your response.  I've been looking at this tool for a while and it looks great.

**Comment by Progi1984** [comment]
@jjmontgo Have you got a sample PPTX with a video embed ? Thanks

**Comment by jjmontgo** [comment]
Sorry no. Just a client with a request. :(

**Comment by Progi1984** [comment]
@jjmontgo Have you got a PowerPoint2007 ?

**Comment by jjmontgo** [comment]
Are you doing an implementation?

**Comment by Progi1984** [comment]
@jjmontgo Yeap. I just search a sample file with a video embed in the file for analyzing the file.

**Comment by Progi1984** [comment]
**Note :** Sample file : [Présentation_Video.pptx](https://github.com/PHPOffice/PHPPresentation/files/159740/Presentation_Video.pptx)

https://download.blender.org/durian/trailer/

**Comment by jjmontgo** [comment]
Nice thanks will check it out

**Comment by Progi1984** [comment]
@jjmontgo Don't worry. I'm on it.

**Comment by Progi1984** [comment]
@jjmontgo Could you test this commit Progi1984@4696fda before integration, please ?

**Comment by jjmontgo** [comment]
Will do thank you

**Comment by Progi1984** [comment]
@jjmontgo Thank you for the feedback :)

**Comment by jjmontgo** [comment]
I tried it using PowerPoint 2003, and the video did not show up.  I do know
the file was embedded given the size of the file.  I'm also guessing maybe
it doesn't work on an old version of powerpoint.

**Comment by jjmontgo** [comment]
Oh I should also mention I was running one of the bundled samples; sample #3

**Comment by Progi1984** [comment]
@jjmontgo Could you test with this file : http://www28.online-convert.com/fr/telecharger-le-fichier/b79f91b6f95a532917d7dbb891a35b76/converted-aa7e9a0e.wmv ?

**Comment by Progi1984** [comment]
@jjmontgo Try with this file, please : https://framadrop.org/r/r-Bmc72blR#1KtVD2xzVrM01onaLYVSMsnu4wmyZ3Nk1Ab3qHXOAr8=

**Comment by jjmontgo** [comment]
Hi!

This had the same result.

When opened in OpenOffice, a 90 x 90 thumbnail for the video appears.
When oepened in Powerpoint 2003, there is no sign of the video (although
the file is clearly in there because of the file size).

I added the video to the slide in Powerpoint 2003.  It appears to leave the
video out of the ZIP file and reference it externally (the powerpoint file
is 43 kb).  I probably have to use another method for inserting it within
the software.

Here is the XML for the slide after inserting the video using the software:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr>
        <p:cNvPr id="1" name=""/>
        <p:cNvGrpSpPr/>
        <p:nvPr/>
      </p:nvGrpSpPr>
      <p:grpSpPr>
        <a:xfrm>
          <a:off x="0" y="0"/>
          <a:ext cx="0" cy="0"/>
          <a:chOff x="0" y="0"/>
          <a:chExt cx="0" cy="0"/>
        </a:xfrm>
      </p:grpSpPr>
      <p:pic>
        <p:nvPicPr>
          <p:cNvPr id="13313" name="Sample image" descr="Sample image"/>
          <p:cNvPicPr>
            <a:picLocks noChangeAspect="1"/>
          </p:cNvPicPr>
          <p:nvPr/>
        </p:nvPicPr>
        <p:blipFill>
          <a:blip r:embed="rId4"/>
          <a:srcRect/>
          <a:stretch>
            <a:fillRect/>
          </a:stretch>
        </p:blipFill>
        <p:spPr bwMode="auto">
          <a:xfrm>
            <a:off x="95250" y="95250"/>
            <a:ext cx="2400300" cy="342900"/>
          </a:xfrm>
          <a:prstGeom prst="rect">
            <a:avLst/>
          </a:prstGeom>
          <a:noFill/>
          <a:ln w="9525">
            <a:noFill/>
            <a:miter lim="800000"/>
            <a:headEnd/>
            <a:tailEnd/>
          </a:ln>
        </p:spPr>
      </p:pic>
      <p:pic>
        <p:nvPicPr>
          <p:cNvPr id="13314" name="PHPPresentation logo"
descr="PHPPresentation logo"/>
          <p:cNvPicPr>
            <a:picLocks noChangeAspect="1"/>
          </p:cNvPicPr>
          <p:nvPr/>
        </p:nvPicPr>
        <p:blipFill>
          <a:blip r:embed="rId5"/>
          <a:srcRect/>
          <a:stretch>
            <a:fillRect/>
          </a:stretch>
        </p:blipFill>
        <p:spPr bwMode="auto">
          <a:xfrm>
            <a:off x="95250" y="952500"/>
            <a:ext cx="2352675" cy="342900"/>
          </a:xfrm>
          <a:prstGeom prst="rect">
            <a:avLst/>
          </a:prstGeom>
          <a:noFill/>
          <a:ln w="9525">
            <a:noFill/>
            <a:miter lim="800000"/>
            <a:headEnd/>
            <a:tailEnd/>
          </a:ln>
        </p:spPr>
      </p:pic>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="13315" name="Video" descr="Video"/>
          <p:cNvSpPr>
            <a:spLocks noRot="1" noChangeAspect="1"/>
          </p:cNvSpPr>
          <p:nvPr>
            <a:videoFile r:link="rId1"/>
          </p:nvPr>
        </p:nvSpPr>
        <p:spPr bwMode="auto">
          <a:xfrm>
            <a:off x="95250" y="1905000"/>
            <a:ext cx="857250" cy="857250"/>
          </a:xfrm>
          <a:prstGeom prst="rect">
            <a:avLst/>
          </a:prstGeom>
          <a:noFill/>
          <a:ln w="9525">
            <a:noFill/>
            <a:miter lim="800000"/>
            <a:headEnd/>
            <a:tailEnd/>
          </a:ln>
        </p:spPr>
        <p:txBody>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:endParaRPr lang="en-US"/>
          </a:p>
        </p:txBody>
      </p:sp>
      <p:pic>
        <p:nvPicPr>
          *<p:cNvPr id="13317" name="sintel_trailer-480p.wmv">*
            <a:hlinkClick r:id="" action="ppaction://media"/>
          </p:cNvPr>
          <p:cNvPicPr>
            <a:picLocks noRot="1" noChangeAspect="1"
noChangeArrowheads="1"/>
          </p:cNvPicPr>
          <p:nvPr>
            <a:videoFile r:link="rId2"/>
          </p:nvPr>
        </p:nvPicPr>
        <p:blipFill>
          <a:blip r:embed="rId6"/>
          <a:srcRect/>
          <a:stretch>
            <a:fillRect/>
          </a:stretch>
        </p:blipFill>
        <p:spPr bwMode="auto">
          <a:xfrm>
            <a:off x="1319213" y="1600200"/>
            <a:ext cx="6507162" cy="3657600"/>
          </a:xfrm>
          <a:prstGeom prst="rect">
            <a:avLst/>
          </a:prstGeom>
          <a:noFill/>
        </p:spPr>
      </p:pic>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr>
    <a:masterClrMapping/>
  </p:clrMapOvr>
  <p:timing>
    <p:tnLst>
      <p:par>
        <p:cTn id="1" dur="indefinite" restart="never" nodeType="tmRoot">
          <p:childTnLst>
            <p:seq concurrent="1" nextAc="seek">
              <p:cTn id="2" restart="whenNotActive" fill="hold"
evtFilter="cancelBubble" nodeType="interactiveSeq">
                <p:stCondLst>
                  <p:cond evt="onClick" delay="0">
                    <p:tgtEl>
                      <p:spTgt spid="13315"/>
                    </p:tgtEl>
                  </p:cond>
                </p:stCondLst>
                <p:endSync evt="end" delay="0">
                  <p:rtn val="all"/>
                </p:endSync>
                <p:childTnLst>
                  <p:par>
                    <p:cTn id="3" fill="hold">
                      <p:stCondLst>
                        <p:cond delay="0"/>
                      </p:stCondLst>
                      <p:childTnLst>
                        <p:par>
                          <p:cTn id="4" fill="hold">
                            <p:stCondLst>
                              <p:cond delay="0"/>
                            </p:stCondLst>
                            <p:childTnLst>
                              <p:par>
                                <p:cTn id="5" presetID="2"
presetClass="mediacall" presetSubtype="0" fill="hold"
nodeType="clickEffect">
                                  <p:stCondLst>
                                    <p:cond delay="0"/>
                                  </p:stCondLst>
                                  <p:childTnLst>
                                    <p:cmd type="call" cmd="togglePause">
                                      <p:cBhvr>
                                        <p:cTn id="6" dur="1" fill="hold"/>
                                        <p:tgtEl>
                                          <p:spTgt spid="13315"/>
                                        </p:tgtEl>
                                      </p:cBhvr>
                                    </p:cmd>
                                  </p:childTnLst>
                                </p:cTn>
                              </p:par>
                            </p:childTnLst>
                          </p:cTn>
                        </p:par>
                      </p:childTnLst>
                    </p:cTn>
                  </p:par>
                </p:childTnLst>
              </p:cTn>
              <p:nextCondLst>
                <p:cond evt="onClick" delay="0">
                  <p:tgtEl>
                    <p:spTgt spid="13315"/>
                  </p:tgtEl>
                </p:cond>
              </p:nextCondLst>
            </p:seq>
            <p:video>
              <p:cMediaNode>
                <p:cTn id="7" fill="hold" display="0">
                  <p:stCondLst>
                    <p:cond delay="indefinite"/>
                  </p:stCondLst>
                  <p:endCondLst>
                    <p:cond evt="onNext" delay="0">
                      <p:tgtEl>
                        <p:sldTgt/>
                      </p:tgtEl>
                    </p:cond>
                    <p:cond evt="onPrev" delay="0">
                      <p:tgtEl>
                        <p:sldTgt/>
                      </p:tgtEl>
                    </p:cond>
                  </p:endCondLst>
                </p:cTn>
                <p:tgtEl>
                  <p:spTgt spid="13315"/>
                </p:tgtEl>
              </p:cMediaNode>
            </p:video>
            <p:seq concurrent="1" nextAc="seek">
              <p:cTn id="8" restart="whenNotActive" fill="hold"
evtFilter="cancelBubble" nodeType="interactiveSeq">
                <p:stCondLst>
                  <p:cond evt="onClick" delay="0">
                    <p:tgtEl>
                      <p:spTgt spid="13317"/>
                    </p:tgtEl>
                  </p:cond>
                </p:stCondLst>
                <p:endSync evt="end" delay="0">
                  <p:rtn val="all"/>
                </p:endSync>
                <p:childTnLst>
                  <p:par>
                    <p:cTn id="9" fill="hold">
                      <p:stCondLst>
                        <p:cond delay="0"/>
                      </p:stCondLst>
                      <p:childTnLst>
                        <p:par>
                          <p:cTn id="10" fill="hold">
                            <p:stCondLst>
                              <p:cond delay="0"/>
                            </p:stCondLst>
                            <p:childTnLst>
                              <p:par>
                                <p:cTn id="11" presetID="2"
presetClass="mediacall" presetSubtype="0" fill="hold"
nodeType="clickEffect">
                                  <p:stCondLst>
                                    <p:cond delay="0"/>
                                  </p:stCondLst>
                                  <p:childTnLst>
                                    <p:cmd type="call" cmd="togglePause">
                                      <p:cBhvr>
                                        <p:cTn id="12" dur="1" fill="hold"/>
                                        <p:tgtEl>
                                          <p:spTgt spid="13317"/>
                                        </p:tgtEl>
                                      </p:cBhvr>
                                    </p:cmd>
                                  </p:childTnLst>
                                </p:cTn>
                              </p:par>
                            </p:childTnLst>
                          </p:cTn>
                        </p:par>
                      </p:childTnLst>
                    </p:cTn>
                  </p:par>
                </p:childTnLst>
              </p:cTn>
              <p:nextCondLst>
                <p:cond evt="onClick" delay="0">
                  <p:tgtEl>
                    <p:spTgt spid="13317"/>
                  </p:tgtEl>
                </p:cond>
              </p:nextCondLst>
            </p:seq>
            <p:video>
              <p:cMediaNode>
                <p:cTn id="13" fill="hold" display="0">
                  <p:stCondLst>
                    <p:cond delay="indefinite"/>
                  </p:stCondLst>
                  <p:endCondLst>
                    <p:cond evt="onNext" delay="0">
                      <p:tgtEl>
                        <p:sldTgt/>
                      </p:tgtEl>
                    </p:cond>
                    <p:cond evt="onPrev" delay="0">
                      <p:tgtEl>
                        <p:sldTgt/>
                      </p:tgtEl>
                    </p:cond>
                  </p:endCondLst>
                </p:cTn>
                <p:tgtEl>
                  <p:spTgt spid="13317"/>
                </p:tgtEl>
              </p:cMediaNode>
            </p:video>
          </p:childTnLst>
        </p:cTn>
      </p:par>
    </p:tnLst>
  </p:timing>
</p:sld>

**Comment by Progi1984** [comment]
```xml
<draw:frame draw:style-name="standard" draw:layer="layout" svg:width="33.866cm" svg:height="19.049cm" svg:x="-2.932cm" svg:y="0.976cm">
	<draw:plugin xlink:href="Media/Wildlife.wmv" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad" draw:mime-type="application/vnd.sun.star.media">
		<draw:param draw:name="Loop" draw:value="false"/>
		<draw:param draw:name="Mute" draw:value="false"/>
		<draw:param draw:name="VolumeDB" draw:value="0"/>
		<draw:param draw:name="Zoom" draw:value="fit"/>
	</draw:plugin>
</draw:frame>
```

**Comment by Progi1984** [comment]
@jjmontgo It seems that uses an external link. I need to find a file generated by Powerpoint with a embed video in the file.

**Comment by jjmontgo** [comment]
I'll try playing around with it today and see if I can get it to embed
internally.

**Comment by Progi1984** [comment]
@jjmontgo You rocks ! Thanks :)

**Comment by Progi1984** [comment]
@jjmontgo Some news ?

**Comment by jjmontgo** [comment]
Sorry not yet as things have been very hectic lately. :(

**Comment by jjmontgo** [comment]
Sorry for taking so long.

I've taken a look at Powerpoint, and it is not possible to embed the video
within the file unless it is converted to Flash and entered as a Flash
object.

Apparently in Powerpoint 2003 and 2007, the video cannot be embedded in the
powerpoint file and has to be in the same directory as the presentation
externally.  In powerpoint 2010, the video can be embedded in the file.  So
it looks like it is a software issue, and perhaps your changes do work but
only in the 2010 version which I don't have.

**Comment by Progi1984** [comment]
@jjmontgo I just asked on Twitter for a sample file : https://twitter.com/Progi1984/status/710453889183649792

**Comment by jdt** [comment]
I've created an empty powerpoint presentation in Office 2010, added the file supplied above via Insert > Video and saved the presentation. No other changes were made. Will this do?

[Presentation1.pptx](https://github.com/PHPOffice/PHPPresentation/files/184880/Presentation1.pptx)

**Comment by Progi1984** [comment]
@jdt Thanks ! That valid my PR #209 :)

Need some unit tests and some documentation. And I push it to develop :)

**Comment by Progi1984** [comment]
Merged in develop branch
