### ISSUE TITLE
XML Writer error

### ISSUE THREAD

**Issue by niklas-agethen** [PHPOffice/PHPPresentation#126]
When saving the generated PowerPoint-file, the following error occurs:

`PHP Fatal error:  Class 'PhpOffice\Common\XMLWriter' not found in ...\src\PhpPresentation\Writer\PowerPoint2007\AbstractPart.php on line 74`

Working with current version (0.4.0) in connection with XAMPP on Windows.
Version 0.3.0 is working fine.

**Comment by Progi1984** [comment]
@niklas-agethen You are not using 0.4.0 but the develop version. Normally, you should have the package PhpOffice\Common in version 0.2.0
```
phpoffice/common": "0.2.*"
```

**Comment by niklas-agethen** [comment]
Any way to make 0.4.0 work properly?
Need new features of that version (non 3D - pie chart).

**Comment by Progi1984** [comment]
@niklas-agethen The version 0.4.0 runs without problem. (https://travis-ci.org/PHPOffice/PHPPowerPoint/builds/69867965).

Could you show me your composer.json ? and the part of your code ? Please :)

**Comment by Nedobr** [comment]
Hello! I have this problem too! Mac OS El Captain, Apache/2.4.16, PHP 5.5.29

Composer:
{
    "require": {
        "phpoffice/phppresentation": "0.5.*"
    }
}

Code: Sample 01 Complex (as is)

**Comment by Progi1984** [comment]
@Nedobr Could you see the #127  ?

**Comment by Nedobr** [comment]
Thank you!
But I resolved this problem: chmod -R 777 path/to/vendor/phpoffice

**Comment by Progi1984** [comment]
@niklas-agethen Have you always got the same problem ?

**Comment by Nedobr** [comment]
@Progi1984 sorry, I'm confused! This problem has not been solved! In 127 using Composer (include 'vendor/autoload.php';), but i can't use it. Can i use PHPPresentation without Composer?

This code in Sample_Header:
use PhpOffice\PhpPresentation\Autoloader;
use PhpOffice\PhpPresentation\Settings;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Slide;
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\AbstractShape;
use PhpOffice\PhpPresentation\DocumentLayout;
use PhpOffice\PhpPresentation\Shape\Drawing;
use PhpOffice\PhpPresentation\Shape\MemoryDrawing;
use PhpOffice\PhpPresentation\Shape\RichText;
use PhpOffice\PhpPresentation\Shape\RichText\BreakElement;
use PhpOffice\PhpPresentation\Shape\RichText\TextElement;
use PhpOffice\PhpPresentation\Style\Bullet;

error_reporting(E_ALL);
define('CLI', (PHP_SAPI == 'cli') ? true : false);
define('EOL', CLI ? PHP_EOL : '<br />');
define('SCRIPT_FILENAME', basename($_SERVER['SCRIPT_FILENAME'], '.php'));
define('IS_INDEX', SCRIPT_FILENAME == 'index');

require_once __DIR__ . '/../src/PhpPresentation/Autoloader.php';
<b>Autoloader::register();</b>

// Set writers
$writers = array('PowerPoint2007' => 'pptx', 'ODPresentation' => 'odp');

But:
Class 'PhpOffice\Common\XMLWriter' not found in <Document_Root>\phpoffice\phppresentation\src\PhpPresentation\Writer\PowerPoint2007\AbstractPart.php on line 74

**Comment by Nedobr** [comment]
@Progi1984 
I downloaded PhpOffice Lib and added this rows in Sample_header PhpPresentation:

require_once __DIR__ . '/../../Common/src/Common/Autoloader.php';
PhpOffice\Common\Autoloader::register();

And problem has resolved.

**Comment by Progi1984** [comment]
Perfect. I have not understand that you have downloaded directly from GIthub.

**Comment by pranshuagrawal** [comment]
@Nedobr Can you please tell me where have you stroed the files of Common Library? I am not getting in which directory should i copy it.
