### ISSUE TITLE
"phpoffice/phppresentation": "dev-master"

### ISSUE THREAD

**Issue by kohloth** [PHPOffice/PHPPresentation#127]
"phpoffice/phppresentation": "dev-master" doesn't work as a composer require.

Problem 1
    - The requested package phpoffice/phppresentation could not be found in any version, there may be a typo in the package name.

**Comment by kohloth** [comment]
Does anyone know what the actual composer require directive is?

**Comment by Progi1984** [comment]
@kohloth 

"phpoffice/phppresentation" is the next version of PHPPowerPoint (#25).

In the mean time, you can use "phpoffice/phppowerpoint".

**Comment by salil1987** [comment]
Hello,
I had the same error "Problem 1
- The requested package phpoffice/phppresentation could not be found in any version, there may be a typo in the package name."

Then I used "phpoffice/phppowerpoint" but after the installation, your example shown on frontpage doesn't work, getting error that  "Fatal error: Class 'PhpPresentation' not found ".

**Comment by alexlavr** [comment]
I have this issue too


```
PHP Fatal error:  Class 'PhpPresentation' not found in /Users/alexlavr/Projects/php-pptx/test1.php on line 11

```

```
$ cat composer.json 
{
    "require": {
       "phpoffice/phppresentation": "dev-master"
    }
}
```

**Comment by Progi1984** [comment]
@alexlavr @salil1987 Have you got always the problem ?

**Comment by salil1987** [comment]
It got solved somehow, and worked out well, now I have implemented the library into joomla as extension, you can create ppts and stuff.
Use "phpoffice/phppowerpoint" instead of "phpoffice/phppresentation"

**Comment by Progi1984** [comment]
@alexlavr @salil1987

I just try this command :
```bash
composer require phpoffice/phppresentation:dev-master
```
or this one :

```bash
composer require "phpoffice/phppresentation" "dev-master"
```

```log
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phpoffice/common (0.2.3)
    Loading from cache

  - Installing phpoffice/phppresentation (dev-master 464b206)
    Cloning 464b206f5de20a0df5e01b3028e7fbcc4989f77b

phpoffice/phppresentation suggests installing ext-gd2 (Required to add images)
Writing lock file
Generating autoload files
```

And ok, no problem.

After that, I try this code :
```php
include 'vendor/autoload.php';

use PhpOffice\PhpPresentation\PhpPresentation;

$oPhpPresentation = new PhpPresentation();
```

And it was ok. 

Have you all ok ?

**Comment by wowpages** [comment]
The Getting Started example (https://github.com/PHPOffice/PHPPresentation) includes this line:

     use PhpOffice\PhpPresentation\PhpPowerpoint;

but that generates an error: Fatal error: Class 'PhpPresentation' not found...

The line in the example should be:

     use PhpOffice\PhpPresentation\PhpPresentation;

**Comment by Progi1984** [comment]
**Note for me :** Improve documentation and search "PhpPowerpoint" in all the repository
