### ISSUE TITLE
Implement Gridlines

### ISSUE THREAD

**Issue by vader88** [PHPOffice/PHPPresentation#129]
I have not been able to find any way to add grid lines to my bar graph. I would like to add major grid lines and be able to set their color.

By the way I think all of these PHPOffice libraries are great. Keep up the good work.

**Comment by jqr108** [comment]
To add to this, I was wondering if there are plans to add other customization features to graphs (no markers and smooth lines on line graphs for example). And is there a way to change the color/thickness of line graph line?

And yeah, to echo vader88, baller library here. Keep on rocking Progi.

**Comment by Progi1984** [comment]
Link to #169 for Outline

**Comment by Progi1984** [comment]
@vader88 : The documentation is here : http://phppresentation.readthedocs.org/en/develop/shapes_chart.html#axis
