### ISSUE TITLE
How do I apply layout?

### ISSUE THREAD

**Issue by Peilun0912** [PHPOffice/PHPPresentation#130]
I have a pptx file which has one slide master and one layout named "Title and picture". The "Title and picture" layout has two placeholders, one for text and another for image. How do I apply the "Title and picture" layout to my slide, and create text and drawing shapes in corresponding placeholders, is there a sample code?

I apologize for my poor english.

**Comment by Peilun0912** [comment]
The code of my example might be:

```php
$objPHPPowerPoint = new PhpPowerpoint();
$currentSlide = $objPHPPowerPoint->getActiveSlide();
$currentSlide->setSlideLayout('Title and picture');
$xmlWriter = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');
$xmlWriter->setLayoutPack(new TemplateBased('./layout.pptx'));
$xmlWriter->save('./result.pptx');
```

"Title and picture" layout has 2 placeholders as mentioned. I wonder if this library can allow me to edit the text of text placeholder and add the image to image placeholder.

**Comment by xdf103** [comment]
Can this be done? Can we edit text in a placeholder and add image to image placeholder? This should be useful feature.
