### ISSUE TITLE
Where is the API docs for PHP Powerpoint?

### ISSUE THREAD

**Issue by vinuf666** [PHPOffice/PHPPresentation#136]
There used to be an API doc for PHPPresentation/powerpoint in Github. now it seems its not linked anymore. There are docs only for PHP Word ??

**Comment by Progi1984** [comment]
You can access to : 
* Documentation : http://phppowerpoint.readthedocs.org/en/latest/
* PHPDoc : http://phpoffice.github.io/PHPPresentation/docs/master/

Anything else ?
