### ISSUE TITLE
ODP Reader can't read odp file

### ISSUE THREAD

**Issue by Peilun0912** [PHPOffice/PHPPresentation#141]
I use Sample_12_Reader_ODPresentation.php to read [my odp file](https://drive.google.com/file/d/0B6dDhi-BapK9cE1Ud1VyNUpOWVU/view?usp=sharing) and get the following result:

![screenclip](https://cloud.githubusercontent.com/assets/4880850/10987599/c93cef16-846f-11e5-9ec6-ecda6596e684.png)

My PHPPresentation version is 0.5.

**Comment by Progi1984** [comment]
@Peilun0912 Could you test this pull request ?

**Comment by Peilun0912** [comment]
@Progi1984 It works! But the result page doesn't show content of RichText, I'm not sure if this is another bug yet.

The result page reading a pptx file the structure of which is similar to odp file can shows content of RichText:

![ppt2007](https://cloud.githubusercontent.com/assets/4880850/11137546/a809f76a-89f3-11e5-9352-161d9d6df525.png)

And this is the result page of odp file:

![odp](https://cloud.githubusercontent.com/assets/4880850/11137557/be91468c-89f3-11e5-8bae-2ab5279c1b83.png)

Thanks for help.

**Comment by Progi1984** [comment]
@Peilun0912 I corrected this. Could you test this pull request ?

**Comment by Peilun0912** [comment]
@Progi1984 Tested and the page shows properties of RichText successful.
