### ISSUE TITLE
How can I get table shape from a slide?

### ISSUE THREAD

**Issue by pei-lun** [PHPOffice/PHPPresentation#142]
I can get shapes except table one via PhpOffice\PhpPresentation\Slide::getShapeCollection() from [this pptx file](https://drive.google.com/file/d/0B6dDhi-BapK9dUN5YmlMR0REQTA/view?usp=sharing). I wonder if table shape has to be retrieved in other way?

**Comment by disiri** [comment]
Hello, Did you find a solution for this issue?

**Comment by Peilun0912** [comment]
No, sorry. It seems to be a bug, the next version may fix it.

**Comment by disiri** [comment]
But you were able to get other shapes except table?
When I tried getting external slide with rectangle shape and text inside using addExternalSlide/addSlide, I can only get the text on the shape but the rectangle as well as its layout are gone. Is it a bug as well? 

Thank you so much.

**Comment by Progi1984** [comment]
@disiri I will work on it in the version 0.8.0.

**Comment by Progi1984** [comment]
@disiri & @Pei-Lun : Now with the develop branch, you can read table shapes in PowerPoint2007.

Could you test it ?

**Comment by Progi1984** [comment]
@disiri & @pei-lun : Fixed in 0.8.0 version.
