### ISSUE TITLE
Has anyone used addExternalSlide?

### ISSUE THREAD

**Issue by tsanami69** [PHPOffice/PHPPresentation#143]
I have the latest build working fine on my server, but I cannot figure out how to use addExternalSlide to load slides from single-slide presentations I have in a library...Could anyone please give an example of code to use this?
Thanks

**Comment by eposjk** [comment]
```php
function appendPresentation($pres, $format, $filename) {
	$reader = IOFactory::createReader($format);
	$pres2 = $reader->load($filename);
	$c = $pres2->getSlideCount();
	for($i=0; $i<$c; $i++)
		$pres->addExternalSlide($pres2->getSlide());
}
```

At least for now (2015) - don't expect it to copy slidemasters.
But it might work for very simple presentations.

**Comment by tsanami69** [comment]
Thanks for the code!
