### ISSUE TITLE
getSlideLayout() always returns BLANK on any opened PPTX file

### ISSUE THREAD

**Issue by tsanami69** [PHPOffice/PHPPresentation#144]
I have tried this on numerous pptx files...
every file I open using:
```php
define('pptxLib', 'thefile.pptx');
$oReaderPPT = IOFactory::createReader('PowerPoint2007');	
$oname = __DIR__."/slides/".pptxLib;
$r = $oReaderPPT->load($oname);	
$r->setActiveSlideIndex(0);
$slide = $r->getActiveSlide();
$slideLayout = $slide->getSlideLayout();
```
$slideLayout always returns BLANK, but the same file when opened in PowerPoint 2010 has every slide with the correct layout.

Is this a bug or a known issues?
Thanks

**Comment by Progi1984** [comment]
@tsanami69 Could you test the PR #147 ?

**Comment by tsanami69** [comment]
Thank you for this.
OK, I've updated the revised files and ran a test...
It now gets the slide layouts BUT seems to return Blank when a slide has a 'Title Only' layout

**Comment by Progi1984** [comment]
@tsanami69 Could you link the file for test ?

**Comment by tsanami69** [comment]
This is the file I'm extracting slides from: www.e-magineda.co.uk/PHPPresentation/myTest/slides/CV8.pptx

This is the file I'm using as the template: www.e-magineda.co.uk/PHPPresentation/myTest/slides/design.pptx

This is the resulting/compiled file: www.e-magineda.co.uk/PHPPresentation/myTest/created/compiled13_02_31.pptx

**Comment by Progi1984** [comment]
@tsanami69 I try to read CV8.pptx with the Sample 12 (PowerPoint2007). I have not found any slide with template "Blank" or "Title Only", just only Layout::TWO_CONTENT & Layout::TITLE_AND_CONTENT & Layout::COMPARISON, and so on.

Could you give me the number of slide, the expected value of template and the returned value ?

**Comment by tsanami69** [comment]
Hi,
CV8.pptx is the origin file that I used to insert slides into the complied13_02_31.pptx.
If you take slide 2 in CV8 the layout is Title Only, but when it's inserted into the compiled file it becomes Two Content...

**Comment by Progi1984** [comment]
**Note for me :** Use code from PhpPresentation/Writer/PowerPoint2007/LayoutPack/TemplateBased.php for extracting layouts and not use the PackDefault

**Comment by tsanami69** [comment]
OK, I tried that and YES it is now picking up the correct Layouts...
Next issue is formatting of content is not correct from the slide master (font sizes etc).
Thanks for your help

**Comment by Tchesco101** [comment]
I am having the same problem as the code would be in this case?

**Comment by Progi1984** [comment]
@tsanami69 I have not yet developed the complete feature ? What have you done ?

**Comment by Progi1984** [comment]
@tsanami69 I updated the PR #147. Could you test it ?

**Comment by Progi1984** [comment]
@tsanami69 : Some news ?

**Comment by Progi1984** [comment]
@tsanami69 Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by SoapWater** [comment]
@Progi1984 I tested it, but still only the background will be copied.

**Comment by Progi1984** [comment]
@tsanami69 : Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
@tsanami69 : Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by tsanami69** [comment]
HI, sorry for the delay in responding...I have checked this and it now works fine.
