### ISSUE TITLE
Saving a presentation is not copying styles or layouts

### ISSUE THREAD

**Issue by ziwar** [PHPOffice/PHPPresentation#150]
If you try to load a presentation that was created in powerpoint or exported from keynote and then save it again without even doing anything, the file will lose styles and layouts:

```
$pptReader = IOFactory::createReader('PowerPoint2007');
$oPHPPresentation = $pptReader->load('Sample.pptx');

$xmlWriter = IOFactory::createWriter($oPHPPresentation, 'PowerPoint2007');
$xmlWriter->save("Sample-copy.pptx");

```
before:
<img width="967" alt="screen shot 2015-11-25 at 10 38 03 am" src="https://cloud.githubusercontent.com/assets/305735/11390166/b74a66d0-9360-11e5-84fc-2233d38068b4.png">

after:

<img width="970" alt="screen shot 2015-11-25 at 10 38 25 am" src="https://cloud.githubusercontent.com/assets/305735/11390171/c852ee84-9360-11e5-9bab-144a6d476730.png">

**Comment by tsanami69** [comment]
I am having the same issue...

**Comment by jmanring** [comment]
I'm seeing the same thing. Looking at the slide xml from the input file and comparing it with what is on the output you'll see all the layout and theming is gone.

**Comment by clubdesarrolladores** [comment]
Same here! please resolve at soon as possible, thanks!

**Comment by Progi1984** [comment]
May be the issue #144 and its pull request would help you...

**Comment by jmanring** [comment]
Still not working. All my slides keep showing up with Blank layout.

**Comment by SoapWater** [comment]
Also tried it, just the background picture will be copied.

**Comment by SoapWater** [comment]
@Progi1984 I also tried it, but still not working. I hope you can fix that soon.

**Comment by Progi1984** [comment]
@ziwar Could you give me your Sample.pptx ? Thanks :smile:

**Comment by jmanring** [comment]
Attached is one presentation I attempted to open and copy a slide to a new presentation.

[Companies.pptx](https://github.com/PHPOffice/PHPPresentation/files/167158/Companies.pptx)

**Comment by Progi1984** [comment]
Hi all, I created a roadmap for managing slide layout : https://github.com/PHPOffice/PHPPresentation/issues/161#issuecomment-195254785

**Comment by Progi1984** [comment]
@jmanring Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@jmanring Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@jmanring It's ok for the main style. Shapes not supported like Geometric form (#117) will be supported in 0.8.0

**Comment by mhasanshahid** [comment]
@Progi1984 I am still have this problem. Can you please guide me how to fix this?

**Comment by mhasanshahid** [comment]
@Progi1984 I am trying to follow this issue, but I am still not sure if its solved or not, because after saving my new pptx file show the same broken layout as images mentioned in this issue.

**Comment by Progi1984** [comment]
@mhasanshahid Which problem do you have ? Could you open a new issue, please ?

**Comment by olegka311** [comment]
i have the same problem. All styles are lost after 
$pptReader = IOFactory::createReader('PowerPoint2007');
$oPHPPresentation = $pptReader->load('Sample.pptx');

$xmlWriter = IOFactory::createWriter($oPHPPresentation, 'PowerPoint2007');
$xmlWriter->save("Sample-copy.pptx");

![pptx](https://user-images.githubusercontent.com/11794752/47868218-5e6d5f00-de0c-11e8-8937-30d7564bc561.png)

**Comment by swati-sapnagroup** [comment]
I am also facing the same issue. Any solution on this problem?

**Comment by tangzhongzhengReal** [comment]
> I am also facing the same issue. Any solution on this problem?

hello, do you find the solution?

**Comment by aymeric451** [comment]
+1

**Comment by niloyniloy** [comment]
does any one found any solution ?

**Comment by pistou** [comment]
It's been 5 years yet this is still an issue. 
I have no clue why this is closed, opening and saving an existing file with a layout breaks the styles.

**Comment by ahorany** [comment]
hello, do you find the solution?

**Comment by ahorany** [comment]
You can use this library it's very fantastic and simple
it will export to PowerPoint, excel, word and another
https://www.tinybutstrong.com/opentbs.php

**Comment by niloyniloy** [comment]
@ahorany its nice that you found have that library. Earlier, I struggled to get the solution. But didnt get in that time. Seems repository owner dont mange this project at all.
