### ISSUE TITLE
Combining multiple presentations

### ISSUE THREAD

**Issue by jmanring** [PHPOffice/PHPPresentation#151]
I have a project that I am working on where we want to pull select slides from several presentation decks and put them in a new deck. It seems like it shouldn't be hard to do by using the getSlide(#) method from the source deck and putting it in the target deck but I don't see a way to add the slide object. It would also be nice to be able to manipulate the slide object before adding it. Anyone have an idea or solution to accomplish this?

**Comment by Progi1984** [comment]
@jmanring With getSlide, you get a Slide object.

You can "addExternalSlide" the object from the new deck.
You can "addSlide" the object  from the new deck.
You can "rebindParent" the new deck from the object.

**Comment by jmanring** [comment]
That seems to work but I lose all the formatting of the slide that I am adding. I think there is another thread that talks about this.

**Comment by Progi1984** [comment]
@jmanring Yes, it's possible. We try to read a maximum of informations, but all is not completly read.

But don't hesitate to create a ticket for each feature which is not read (with sample files), i try to improve it. Thanks
