### ISSUE TITLE
How can get the background color of the slide ?

### ISSUE THREAD

**Issue by Tchesco101** [PHPOffice/PHPPresentation#152]
I'm trying to get the background color of the slide without success , how can I get him in rgb ?

**Comment by Progi1984** [comment]
Code: 
http://www.officeopenxml.com/prSlide-background.php

**Comment by Tchesco101** [comment]
Thanks for answering! So really there is no ready function PhpPresentation library that returns me the data background , correct? I create starting of the data you send me the link . Correct?

**Comment by Progi1984** [comment]
Linked to the PR #158 

@Tchesco101 Could you test the PR #158 ?

I added a reader and writer for PowerPoint2007 & OpenDocument.

You can set and get Color & Image Backgrounds.
Look at the Sample 15 for the implementation.
Samples 12 has been improved for displaying background in the tree.
Thank you for your feedback.

Documentation & Unit test come after your validation. Thanks in advance.

**Comment by Progi1984** [comment]
@Tchesco101 Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
@Tchesco101 Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
@jdleung If you test it, I can merge into develop branch, for next release.

Poke @Tchesco101

**Comment by jdleung** [comment]
@Progi1984 sure. good to hear that. Now I place an image as a background.

**Comment by Progi1984** [comment]
@jdleung So the PR is ok for you ?

**Comment by jdleung** [comment]
Is Pull Request complex?. You know I just wander on github and download some projects.  But if I don't disturb your job, I will take a try.

**Comment by Progi1984** [comment]
@jdleung No you can't take part to this project, with pull request.

Link : https://yangsu.github.io/pull-request-tutorial/
Link : https://help.github.com/articles/using-pull-requests/

@jdleung So ok for this PR ?

**Comment by jdleung** [comment]
@Progi1984 I clicked the "Fork" and "New Pull Request", still don't understand how it works. May this help.

**Comment by Progi1984** [comment]
@jdleung Before doing some pull request, you need to commit some changes.

**Comment by jdleung** [comment]
@Progi1984 Where to commit? or just say yes to you?

**Comment by Progi1984** [comment]
@jdleung You commit in your fork of the project.

**Comment by jdleung** [comment]
@Progi1984 I think I followed your instruction and completed. I clicked "Fork" at top-right, then clicked "412 Commits" at the left.

**Comment by Progi1984** [comment]
@jdleung You should find a mentor for helping you. 
Some links : https://try.github.io/levels/1/challenges/1 / https://www.codecademy.com/learn/learn-git / https://help.github.com/articles/good-resources-for-learning-git-and-github/

Sorry, I need to advance in PHPPresentation.

**Comment by Progi1984** [comment]
@Tchesco101 Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
Implemented in develop branch. I close this issue.
