### ISSUE TITLE
Maintain aspect ratio?

### ISSUE THREAD

**Issue by bgetkin** [PHPOffice/PHPPresentation#153]
I am successfully loading an existing pptx file that has an aspect ratio of 16:9, adding text elements to it then writing to a new pptx file. However, the new file has an aspect ratio of 4:3.  Is there a way to define the ratio for the new file, or set it to maintain original, that I'm not finding.?

Code:
```php
$pptReader = IOFactory::createReader('PowerPoint2007');
$objPHPPowerPoint = $pptReader->load('template.pptx');

// Adding text elements here

$oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');		
$oWriterPPTX->save('new.pptx');
```

**Comment by Progi1984** [comment]
@bgetkin Hi Could you give us two file for searching between the two ? Thanks :)

**Comment by bgetkin** [comment]
Here are the 2 files from the above example. In the actual program there are many more pages, but this should give you enough information to look into the issue.

[template.pptx](https://github.com/PHPOffice/PHPPresentation/files/77504/template.pptx)
[new.pptx](https://github.com/PHPOffice/PHPPresentation/files/77503/new.pptx)

Let me know if you need anything else and thank you for your help.

**Comment by Progi1984** [comment]
OK...

I see the problem. This issue is linked to #161.

**Comment by Progi1984** [comment]
@bgetkin  I created a roadmap for managing slide layout : https://github.com/PHPOffice/PHPPresentation/issues/161#issuecomment-195254785

**Comment by Progi1984** [comment]
@bgetkin Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@bgetkin Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@bgetkin Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@bgetkin Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@bgetkin Run ok with the PR #230
