### ISSUE TITLE
Allow Loop Continuously to be set to true

### ISSUE THREAD

**Issue by pickupman** [PHPOffice/PHPPresentation#154]
PowerPoint 2007 file format can be played continuously with the following code added to Writer/PowerPoint2007/PptsProps.php at Line 44 adding:

```
// Enable slideshow to autoloop
$objWriter->startElement('p:showPr');
$objWriter->writeAttribute('loop', '1');
$objWriter->endElement();
```

This adds a p:showPr child element to p:presentationPr that allows the slideshow to keep playing until [Esc] is pressed.

**Comment by Progi1984** [comment]
Note for Libreoffice Impress users : https://ask.libreoffice.org/en/question/92/loop-an-impress-presentation/

OpenXML :
* http://www.datypic.com/sc/ooxml/e-p_showPr-1.html

OpenDocument :
* http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#attribute-presentation_endless

```xml
<!-- content.xml -->
			<presentation:settings presentation:endless="true" presentation:pause="P0D" presentation:mouse-visible="false"/>
		</office:presentation>
	</office:body>
</office:document-content>
```

@pickupman Could you give a screenshot of Powerpoint for defining the slideshow endless ? Can you define a pause between each presentation ?

**Comment by pickupman** [comment]
@Progi1984 here is a screenshot from PowerPoint 2007. You only have the option to loop continously. No option to set a delay/pause between presentations.

![clipboard01](https://cloud.githubusercontent.com/assets/1220279/11690483/cd31e05e-9e64-11e5-9b8f-920d1b12f914.jpg)

**Comment by pickupman** [comment]
Here is the element for the ODPresentation Writer class in Content.php at line 302:
```
// Enable slideshow to autoloop
 $objWriter->startElement('presentation:settings');
 $objWriter->writeAttribute('presentation:endless', "true");
 $objWriter->endElement();
```

**Comment by Progi1984** [comment]
@pickupman : Could you test the PR #157, please ? Thanks :)

**Comment by Progi1984** [comment]
@pickupman : Just fixed your request. Could you give me feedback, please :)

**Comment by Progi1984** [comment]
@pickupman Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
@pickupman Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
@pickupman Have you got time for testing the Pull Request before integration in develop branch ? Thanks for your feedback.

**Comment by Progi1984** [comment]
Merged in develop branch.

**Comment by toleabivol** [comment]
@Progi1984 how to set a delay in seconds for each slide (pause during loop) ?
 I found to be able only to set the `isLoopContinuouslyUntilEsc` to true
