### ISSUE TITLE
PowerPoint2007 : Read/Write SlideLayout

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPPresentation#161]
> A slide layout is essentially a template design which can be applied to one or more slides, defining the default appearance and positioning of objects on the slide.

The appliance would be to load data from the slide layout in a first time.
In a second time, we load data from slide.xml and overwrite data from layout.

Links : 
* http://officeopenxml.com/prSlideLayout.php
* https://msdn.microsoft.com/en-us/library/office/gg278311.aspx

**Comment by Progi1984** [comment]
Linked issues :
* #153 : Width & Height are in the slide layout XML, not the slide XML

**Comment by Progi1984** [comment]
Some analysis :
* Layout is linked to slide
* Layout is a group of placeholder
* A placeholder is linked or not to a shape

**Comment by Progi1984** [comment]
@vincentKool Could i use your work (https://github.com/PHPOffice/PHPPresentation/compare/develop...vincentKool:office2007ReadSlideLayout) as base for this issue ?

**Comment by Progi1984** [comment]
@vincentKool Could i use your work (https://github.com/PHPOffice/PHPPresentation/compare/develop...vincentKool:office2007ReadSlideLayout) as base for this issue ?

**Comment by Progi1984** [comment]
@vincentKool Could i use your work (https://github.com/PHPOffice/PHPPresentation/compare/develop...vincentKool:office2007ReadSlideLayout) as base for this issue ?

**Comment by Progi1984** [comment]
The PR is opened : https://github.com/PHPOffice/PHPPresentation/pull/230

**Comment by shashank2104** [comment]
@Progi1984 @vincentkool Thank you guys for trying to solve these issues. Btw can we get an update on this particular issue? Any commits that you've added to the library as a whole? 
Yes, I'm able to create a new ppt with most of the features working well for me but it'd be great if I could get an example of loading/copying base layout of the master ppt and saving it into a new one. 

I did try the one you mentioned (below) but this code copies only the first 2 slides (something weird): 
```
$pptReader = IOFactory::createReader('PowerPoint2007');
$objPHPPowerPoint = $pptReader->load('template.pptx');

// Adding text elements here

$oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');        
$oWriterPPTX->save('new.pptx');
```

A simple working example of load/save would be awesome.  
Thanks.

**Comment by vincentKool** [comment]
I've made a new pull request with Progi1984 [PR into Progi1984:issue161](https://github.com/Progi1984/PHPPresentation/pull/4) in order to update PR #230

**Comment by Progi1984** [comment]
@vincentKool I just merged it ;)

@shashank2104 Have you tried the PR #230 ?

For informations, reading and writing will never be perfect, while PhpPresentation can't abstract any part in a powerpoint. The road is long but the road is open (Poke @framasoft).

**Comment by Progi1984** [comment]
@vincentKool Mission of the week end :)

Try files #150 / #153 / #210 (if features are missing in PhpPresentation, I will create tickets for implementation in next version)...
If OK, create documentation...
If OK, merge the PR :+1:

**Comment by Progi1984** [comment]
PR #230 Merged in develop branch
