### ISSUE TITLE
How to install composer correctly?

### ISSUE THREAD

**Issue by jdleung** [PHPOffice/PHPPresentation#164]
Since failed on installing the project without composer, I now want to try installing it with composer.

By now, the composer has been installed successfully via terminal. but it did not create file "vendor/autoload.php", how can I run it and make it create such directory and files.

Mac, using MAMP as a server.

Thanks.

**Comment by Progi1984** [comment]
For installing, you must use composer in command line :

```bash
composer require phpoffice/phppresentation
```

**Comment by jdleung** [comment]
I input command line "composer require phpoffice/phppresentation", it shows "no such command".
Sorry for knowing nothing about composer.

I installed composer and go to this last step, command line in terminal:
*php composer.phar*

it shows composer help things like:
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0-dev (03299ff075236be27be356498d6c64def973fe41) 2016-01-10 20:34:53

Usage:
  command [options] [arguments]

Options:
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
.......

what's the next step I need to do so that I can install the library and create the file "vendor/autoload.php"?

Thanks.

**Comment by Progi1984** [comment]
Do :
```
php composer.phar require phpoffice/phppresentation
```

**Comment by jdleung** [comment]
Followed your instruction, I got the following message. The autoload file may have been created successfully, but maybe in somewhere, not in PHPPresentation folder "vendor". How can I make it works in the next step? Thanks.

Using version ^0.5.0 for phpoffice/phppresentation
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phpoffice/common (0.2.3)
    Downloading: 100%         

  - Installing phpoffice/phppresentation (0.5.0)
    Downloading: 100%         

phpoffice/phppresentation suggests installing ext-gd2 (Required to add images)
Writing lock file
Generating autoload files

**Comment by jdleung** [comment]
OK, I found the autoload file in user/myname/. 

I moved it to PHPPresentation folder, and it finnally works for me.

Thanks.

BW, still I want to know how to make manual installation work. See another issue created by me ;-)

**Comment by Progi1984** [comment]
@jdleung Just answered in the other issue.
