### ISSUE TITLE
Line 28, require_once(../vendor/autoload.php): failed to open stream: No such file or directory in sample_header.php

### ISSUE THREAD

**Issue by pranshuagrawal** [PHPOffice/PHPPresentation#166]
So I tried working upon it using XAMPP, I have successfully copied all the contents to my XAMPP folder but as soon as I am trying to open the sample files it is giving me an error saying require_once(../vendor/autoload.php): failed to open stream: No such file or directory in sample_header.php. How can I resolve this issue?

**Comment by Progi1984** [comment]
Do you have used Composer ?

**Comment by pranshuagrawal** [comment]
No I have not used composer. Yes after removing that line (which was intend to be used when you have installed it using composer) the code works fine. Thank you.
