### ISSUE TITLE
Not getting any idea how to change the color of the line graph?

### ISSUE THREAD

**Issue by pranshuagrawal** [PHPOffice/PHPPresentation#169]
So I am facing three issues when using `charts`.

1. How to change the color of line and points when using line chart?
2. How to changes the font size of the points values?
3. How to align points values to the top when using area chart (they are vertically in middle as of now.)?

**Comment by pranshuagrawal** [comment]
Any progress in this?

**Comment by Progi1984** [comment]
It's on the pipe for the milestone 0.7.0.

**Comment by developerMediaXray** [comment]
In the writer/powerpoint2007/chart.php on line 1909 just below c:tx I put the following to remove the markers.
`
            // c:marker
            $objWriter->startElement('c:marker');

            // c:marker
            $objWriter->startElement('c:symbol');
            $objWriter->writeAttribute('val', 'none'); // Marker style
            //$objWriter->writeAttribute('size', '7'); // Marker size
            $objWriter->endElement();

            $objWriter->endElement();`

**Comment by Progi1984** [comment]
In my develop branch,
* Marker (Size & Symbol) in Line & Scatter Chart is now customizable

**Comment by Progi1984** [comment]
@pranshuagrawal For the third point, could you describe what you want ? And have you got some Office Powerpoint screenshots of the render and/or the options ? Thanks for advance

**Comment by developerMediaXray** [comment]
Is there a sample of how to customize the line chart yet?

**Comment by Progi1984** [comment]
@developerMediaXray Yes, just here : https://github.com/Progi1984/PHPPresentation/commit/c25b5537c66f7fdb145cf222537c67714e1504c2#diff-5b63fbb4a824b89cff6871bc7f47da0b

**Comment by Progi1984** [comment]
@pranshuagrawal Some news ?

**Comment by Progi1984** [comment]
@developerMediaXray May be you can help me on the third point of @pranshuagrawal : I don't understand what he wants :)

**Comment by Progi1984** [comment]
Note : http://superuser.com/questions/647933/lo-calc-why-are-data-labels-placement-options-greyed-out

**Comment by Progi1984** [comment]
@pranshuagrawal : Some documentation have been added and samples have been modified
