### ISSUE TITLE
Formatting the axis on a line chart

### ISSUE THREAD

**Issue by developerMediaXray** [PHPOffice/PHPPresentation#171]
Is there a way to make it show every 7th data label on the line charts axis? I have data being pulled for everyday of the month, and to reduce clutter (currently it shows every other day) I would like to have it only show the first day and every 7 days after that on the label only ( I still want to keep the data the same).
##

**Comment by Progi1984** [comment]
@developerMediaXray Do you know how to do it in PowerPoint / LibreOffice ?

If yes, could you give us some screenshots and a sample with the feature. Thanks.

**Comment by Progi1984** [comment]
@developerMediaXray PhpPresentation 0.8.0 has been released. I would like to solve your issue for 0.9.0. Could you answer to my question ?

**Comment by kailashgajara** [comment]
@Progi1984 I found this issue just now. I also want to have similar feature where I can set interval unit. I will try explaining what @developerMediaXray was asking and how to do it in powerpoint.

Say on X-Axis, I have 6000 values. So my line chart shows all values. Of course I do not have space to show all values on x-axis. (say my x-axis is timestamp). So I want to show only 5-6 values on horizontal axis but my graph should plot all values. See image below:

<img width="512" alt="php-presentation-example" src="https://cloud.githubusercontent.com/assets/4597121/25664333/eb633080-3037-11e7-83ae-afa6a770d714.png">

Is that something you think we can do with current version of php-presentation?

**Comment by kailashgajara** [comment]
@Progi1984 Please find attached live pptx file which has 1000 values in x-axis. I have created this manually. In powerpoint, under Axis Points, under Labels, I have specified 100 for "Specify interval unit" option. 
[Presentation1.pptx](https://github.com/PHPOffice/PHPPresentation/files/981443/Presentation1.pptx)

**Comment by Progi1984** [comment]
@kailashgajara : Hi, Could you
- download this file : [Sample_05_Chart_Line.pptx.zip](https://github.com/PHPOffice/PHPPresentation/files/1022125/Sample_05_Chart_Line.pptx.zip)
- rename it to .pptx
- verify in the first chart that interval unit is 5 

Thanks

**Comment by kailashgajara** [comment]
@Progi1984 Yes, interval unit is 5. I verified it on windows. Although it did ask to repair. Btw on mac office 2008, even after repair, all slides were empty. In windows all slides came out to be fine.

**Comment by Progi1984** [comment]
@kailashgajara : 
> @Progi1984 Yes, interval unit is 5. I verified it on windows. Although it did ask to repair. Btw on mac office 2008, even after repair, all slides were empty. In windows all slides came out to be fine.

Did the generated file on PowerPoint on Windows asked you to repair ?
Did the generated file on PowerPoint on Mac asked you to repair ?

**Comment by kailashgajara** [comment]
@Progi1984 Yes, both windows and mac asked me to repair. In windows, after repair (there were like 3-4 popups), it showed all charts fine but in mac even after repair, all slides where empty. Full white.

**Comment by Progi1984** [comment]
Fixed in #546
