### ISSUE TITLE
Adding Notes Breaks "Print Slide With Notes"

### ISSUE THREAD

**Issue by JewrassicPark** [PHPOffice/PHPPresentation#179]
You can print/save powerpoints that show the slide with the notes below it. Adding notes through phppresentation causes this feature to break and only the notes are displayed in the printout.

**Comment by Progi1984** [comment]
@JewrassicPark Could you give us two files ?
* a file generated with PHPPresentation with the bug
* the same file where you have fixed the bug (opened in PowerPoint, and fixed in this one)

**Comment by JewrassicPark** [comment]
The first file is generated and has the big. 

I couldn't directly fix the bug in powerpoint. Once the slide was formatted this way I don't see a way to reset it so the bug isn't present. I included a second slide in the presentation that displays correctly. 

[notes-brokenpriview.pptx](https://github.com/PHPOffice/PHPPresentation/files/110131/notes-brokenpriview.pptx)


[notes-brokenpriview-fixed.pptx](https://github.com/PHPOffice/PHPPresentation/files/110132/notes-brokenpriview-fixed.pptx)

**Comment by JewrassicPark** [comment]
I've been able to modify the slide writer for powerpoint2007 to have the preview display but I'm having issue with the dimensions of the preview across formats. 

Right now when you add a note you create a rich text shape in order to alter the text 

`$text = $note->createRichTextShape()->setHeight(300)->setWidth(600);
`
The slide writer uses the dimensions of that richtextshape to calculate the offsets and extents of the note, which are the dimensions used to display the preview. My issue is with getting the proper dynamic value for this for each powerpoint layout.

**Comment by JewrassicPark** [comment]
I've updated my fork with the new writeNote function for the powerpoint2007 slide writer. I already have the pull request open for the animation, what's the best way to merge this as well?

**Comment by Progi1984** [comment]
@JewrassicPark I'll try to implement your patch.

Bug with Sample_09, that doesn't seem to work.

![screen shot 02-13-16 at 10 30 am](https://cloud.githubusercontent.com/assets/1533248/13026978/e8c4a62e-d23c-11e5-8631-fbd1e3b26857.PNG)

Thanks for your help for fixing it before merging it :)

**Comment by Progi1984** [comment]
@JewrassicPark Some news ?

**Comment by Progi1984** [comment]
@JewrassicPark Some news ?

**Comment by JewrassicPark** [comment]
Sorry, what's the current issue on this? I can't produce any bugs in my print with notes currently. I still have inconsistent errors having notes at all though.

**Comment by Progi1984** [comment]
@JewrassicPark Check this comment : https://github.com/PHPOffice/PHPPresentation/issues/179#issuecomment-183632619

**Comment by JewrassicPark** [comment]
In your sample you have 

`$oRichText = $oNote->createRichTextShape()->setHeight(300)->setWidth(600)->setOffsetX(170)->setOffsetY(180);;
`

This is how I set the notes: 

```
$layout = $objPHPPresentation->getLayout();
$layoutCX = $layout->getCX($layout::UNIT_PIXEL); 
$layoutCY = $layout->getCY($layout::UNIT_PIXEL); 
$oRichText = $oNote->createRichTextShape()->setHeight($layoutCY)->setWidth($layoutCX);
```

I changed only those lines in your sample and the notes looked correct for me.

**Comment by Progi1984** [comment]
@JewrassicPark : But with theses changes : https://github.com/Progi1984/PHPPresentation/commit/5c3e87482da83e1d289cabecb3e377efbba94171 ?

**Comment by JewrassicPark** [comment]
Sorry, yes, I am using that writer currently

**Comment by Progi1984** [comment]
@JewrassicPark Could you test this file : https://framadrop.org/r/Z3GR8dCTmY#OZ+pXMjw+koMEOUt9SrO3mb04pD+WdPOnuXtJNrAlcU=
 ?

Is it ok for you ? Thanks

**Comment by JewrassicPark** [comment]
No, I get a repair notice when opening it (windows 10, office 2013) and I don't see any notes once the repair is complete.

**Comment by Progi1984** [comment]
@JewrassicPark I think I'm better : i have no interfact in LibreOffice.

https://framadrop.org/r/6FrPIumUDA#9k8x+j2vP0UeZbFFQQ6OeNY4qF6qemN0JMOZ0gkmfew=

**Comment by Progi1984** [comment]
@JewrassicPark Some news ?

**Comment by JewrassicPark** [comment]
I still don't see the slide in the notes print on yours. I'll take a look but since the only thing I changed in your example was the two lines above it's probably a difference in our code bases. I'm fairly certain I submitted everything that I added I'll try to double check

**Comment by Progi1984** [comment]
@JewrassicPark Shit ! We are nearly to the solution. 

What is the difference between your code and this branch : https://github.com/PHPOffice/PHPPresentation/compare/develop...Progi1984:issue179 ?

**Comment by JewrassicPark** [comment]
This is the slide writer in powerpoint2007 that im currently using 

https://framadrop.org/r/5lGC2h0D0n#PPNN/aGk23MMjN9VFmJsoh7ov5VHVZ7sC6PijvElYCM=

**Comment by Progi1984** [comment]
@JewrassicPark I have made a simple change. Could you test :  https://framadrop.org/r/mH8j3Nurmc#viqd4C7vkcsB+L/rGmLt0tY7nrWjLjSDIEOgYVZk4Vo= ?

**Comment by JewrassicPark** [comment]
Close: http://i.imgur.com/Z5zUrXy.jpg

The positioning is still off. Did you definitely make the changes in: 

https://github.com/PHPOffice/PHPPresentation/issues/179#issuecomment-193825835

**Comment by Progi1984** [comment]
@JewrassicPark I have done the change in sample :

https://framadrop.org/r/fhevpIMmxd#abbwOh9RbTjLOfhRHbVkRlhHemvqI4ewZe1tLtreBAY=

Could you test ?

**Comment by JewrassicPark** [comment]
Not quite 

http://i.imgur.com/PdGI6Wy.jpg

**Comment by Progi1984** [comment]
[Sample_09_SlideNote.pptx](https://github.com/PHPOffice/PHPPresentation/files/183743/Sample_09_SlideNote.pptx)

```php
$oRichText = $oNote->createRichTextShape()
    ->setHeight($oLayout->getCY($oLayout::UNIT_PIXEL))
    ->setWidth($oLayout->getCX($oLayout::UNIT_PIXEL))
    ->setOffsetX(0)
    ->setOffsetY(0);
```
![screen shot 03-22-16 at 09 42 am](https://cloud.githubusercontent.com/assets/1533248/13946050/6a57d31c-f012-11e5-884e-10f857b03283.PNG)

[Sample_09_SlideNote.pptx](https://github.com/PHPOffice/PHPPresentation/files/183747/Sample_09_SlideNote.pptx)

```php
$oRichText = $oNote->createRichTextShape()
    ->setHeight($oLayout->getCY($oLayout::UNIT_PIXEL))
    ->setWidth($oLayout->getCX($oLayout::UNIT_PIXEL))
    ->setOffsetX(170)
    ->setOffsetY(180);
```
![screen shot 03-22-16 at 09 43 am](https://cloud.githubusercontent.com/assets/1533248/13946076/8c9b908a-f012-11e5-9912-f17aa952cfec.PNG)

**Comment by Progi1984** [comment]
@JewrassicPark Just tested on Office2007. Could you test on your side with latest files ?

**Comment by Progi1984** [comment]
@JewrassicPark Some news ?

**Comment by JewrassicPark** [comment]
Yeah the two pages you linked  here https://github.com/PHPOffice/PHPPresentation/issues/179#issuecomment-199704145 

display the same for me as they do in your screenshots

**Comment by Progi1984** [comment]
Yeah ! Bug fixed :)
