### ISSUE TITLE
Are setFillPath and AddGradientStop removed from Fill?

### ISSUE THREAD

**Issue by 5t111111** [PHPOffice/PHPPresentation#182]
I'm trying to update PHPPowerPoint used in our project to the latest PHPPresentation, but `Fill` class no longer has both `setFillPath` and `AddGradientStop`. 

I've also tried to check someting like changelog or file's history. However, I can't find them because PHPPresentation repository doesn't seem to include previous changes.

Why are setFillPath and AddGradientStop removed? Please let me know if there are any alternatives.

**Comment by Progi1984** [comment]
@5t111111 Which version do you have ? 

I look for in an old version (https://phppowerpoint.codeplex.com/SourceControl/latest#trunk/Classes/PHPPowerPoint/Style/Fill.php) and **setFillPath** / **addGradientStop ** are not present.

With the version (or the code of the library), I will help you to find a solution.

**Comment by 5t111111** [comment]
@Progi1984 Sorry but I have investigated further this issue after reading your above comment, and found those properties are added by someone after forking the original PHPPowerPoint :cry: 

I'm going to close this issue, thank you for your help though!

**Comment by Progi1984** [comment]
If you give me the fork, I can implement it in Phppresentation. No ?

**Comment by Progi1984** [comment]
@5t111111 If you give me the fork, I can implement it in Phppresentation. No ?
