### ISSUE TITLE
Slide Templates & Layouts 

### ISSUE THREAD

**Issue by jrking4** [PHPOffice/PHPPresentation#185]
Hi,
I am working on implementing Slide Templates. And I can call the template fine. And set a Layout on the slide. However how do I edit the text or add a shape at the coordinates of the placeholders on the slide template?  For example if i call the following: 
` $currentSlide->setSlideLayout(Layout::TITLE_AND_CONTENT);`

How can I then edit the headline and insert content in the placeholder boxes?  The layout function seems kind of pointless without this.  Any feedback would be appreciated.

**Comment by jrking4** [comment]
Hi @Progi1984, is this something that hasnt been implemented yet? If you give me some details on what is built and what is needed, I may be able to tackle it for you

**Comment by Progi1984** [comment]
@jrking4 I created a roadmap for managing slide layout : https://github.com/PHPOffice/PHPPresentation/issues/161#issuecomment-195254785

**Comment by Progi1984** [comment]
@jrking4 Could you test the PR #230 ?

**Comment by Progi1984** [comment]
@jrking4 Could you test the PR #230 ?
