### ISSUE TITLE
How do you set orientation on a Presentation?

### ISSUE THREAD

**Issue by bpineda** [PHPOffice/PHPPresentation#196]
Awesome project, guys. Just a question. On the doc it says that it supports now printing orientation, yet, I can't find any example to set up a vertical presentation. Did I miss something?

**Comment by Progi1984** [comment]
@bpineda Could you give us sample generated file with some screenshots from PowerPoint, please ?

**Comment by bpineda** [comment]
I wan to change from this layout:
![screenshot 2016-03-15 13 55 58](https://cloud.githubusercontent.com/assets/1189433/13792186/4eb86ee8-eab6-11e5-9ddf-64cfcd798673.png)

To this one: 
![screenshot 2016-03-15 13 56 34](https://cloud.githubusercontent.com/assets/1189433/13792188/504e9494-eab6-11e5-90a4-9325822e0223.png)
I can't find code to generate the vertical type presentation.

**Comment by Progi1984** [comment]
@bpineda Have you tried this :

```php
$oDocumentLayout = new DocumentLayout();
$width = $oDocumentLayout->getCX();

$oPresentation = new PhpPresentation();
$oPresentation->setLayout($oDocumentLayout);

```

**Comment by bpineda** [comment]
You are my savior. It worked perfectly. Thanks a bunch. If you guys need help, I can help around with documentation and examples.

**Comment by Progi1984** [comment]
@bpineda We are always open to help.
