### ISSUE TITLE
Alpha channel on fill colours?

### ISSUE THREAD

**Issue by Dayjo** [PHPOffice/PHPPresentation#201]
Hello!

Just saw https://github.com/PHPOffice/PHPPresentation/issues/199 but as it has no content, plus it contains multiple issues, I thought I'd write this up.

I'm very new to this library, but it seems great and mostly covers everything I need. However, I'm trying to add transparency to fill colour. Looking at the code, it seems like it's using ARGB (and in the Color class handles ARGB channels), however in the saved out presentation, it seems to always use a 100% alpha channel. 

Taking the Linear gradient example from the samples directory the following code makes the background a gradient;
```php
$shape->getFill()->setFillType(Fill::FILL_GRADIENT_LINEAR)->setRotation(90)->setStartColor(new Color( 'FF4672A8' ))->setEndColor(new Color( 'FF000000' ));
```

I assumed by changing the prefixing `FF` (alpha channel) that this would just work but it appears not. Is there anything special needed to get Alpha transparency to work?

Thanks for all your hard work!

**Comment by Dayjo** [comment]
Looking deeper into the code (though I don't really have the time right now), looks like this shouldn't be too difficult to implement. I may put together a pull request once I've gone through the contributing notes.

**Comment by Dayjo** [comment]
Ok, I've given this a go following the documentation but to no avail. 

I figured that it would just be a matter of adding the alpha element to the srgb Clr element as per;

```xml
<a:srgbClr val="4672A8">
    <a:alpha val="1"/>
</a:srgbClr>
```

But when opening in Keynote and Google Slides (ironically, I don't have PowerPoint), whatever I put in the value of the alpha element, it ends up with an alpha value of 0. Perhaps I'm missing something?

**Comment by Progi1984** [comment]
@Dayjo I just add some improvements (and some code deduplications) ;).

**Comment by Progi1984** [comment]
Merged in develop branch
