### ISSUE TITLE
Can't hide marker on line chart for pptx (0.7.0)

### ISSUE THREAD

**Issue by Napryc** [PHPOffice/PHPPresentation#211]
Hi,

I'm trying to hide the marker from a line chart, however, setting:
`$lineMarker->setSymbol(\PhpOffice\PhpPresentation\Shape\Chart\Marker::SYMBOL_NONE);
`
seems not enough. 

I've solved this issue by adding the following else clause in the writeSeriesMarker function of PptCharts.php file:

```
else {
    $objWriter->startElement('c:marker');
    $objWriter->startElement('c:symbol');
    $objWriter->writeAttribute('val', $oMarker->getSymbol());
    $objWriter->endElement();
    $objWriter->endElement();
}        
```
##

**Comment by Progi1984** [comment]
@Napryc I just modified your fix. Could you test the PR #286 ?

**Comment by Progi1984** [comment]
@Napryc Some feedback, please.

**Comment by Progi1984** [comment]
@Napryc Some feedback, please :)

**Comment by Progi1984** [comment]
Fixed in develop branch
