### ISSUE TITLE
Can't format value of Pie chart pptx (0.7.0)

### ISSUE THREAD

**Issue by Napryc** [PHPOffice/PHPPresentation#212]
Hi,

formatting values in pie chart is not working. Doing a modification in the function writeTypePie of PptCharts.php file solved it for me.

After line 1383
`$objWriter->startElement('c:dLbls');`
I've added the following code:

```
if ($series->hasDlblNumFormat()) {
   $objWriter->startElement('c:numFmt');
   $objWriter->writeAttribute('formatCode', $series->getDlblNumFormat());
   $objWriter->writeAttribute('sourceLinked', '0');
   $objWriter->endElement();
}
```
##

**Comment by Progi1984** [comment]
@Napryc I just modified your fix. Could you test the PR #287 ?

**Comment by Progi1984** [comment]
@Napryc Some feedback, please.

**Comment by Progi1984** [comment]
@Napryc Some feedback, please.

**Comment by Progi1984** [comment]
Fixed in develop branch
