### ISSUE TITLE
Read PPT comments

### ISSUE THREAD

**Issue by nacerAddineNabih** [PHPOffice/PHPPresentation#222]
hello, 

i'm trying to read comments from power point. i use the samples for tests but when i add comments to a slide in the presentation, i can't read them. 
it is possible to get comments with PHPPowerPoint ? or it's not included in the library.
if it's not included, how i can use the xml parser to read them ?
( sorry but im a novice and i have to read all informations in a PPT file for my school project )

Thank you.
##

**Comment by Progi1984** [comment]
Fixed in #226 (for PowerPoint97 & PowerPoint2007)
