### ISSUE TITLE
Background colors are pale

### ISSUE THREAD

**Issue by slewitan** [PHPOffice/PHPPresentation#233]
When I produced a presentation using the development code I was getting pale background colors, the transparency was getting set to 76%. (This was not the case with the release code.)
I was able to fix it by adding `if(!is_null($alpha)) $alpha = 100;` to PHPPresentation\src\PhpPresentation\Writer\PowerPoint2007\AbstractDecoratorWriter.php

``` php
    protected function writeColor(XMLWriter $objWriter, Color $color, $alpha = null)
    {
        if (is_null($alpha)) {
            $alpha = $color->getAlpha();
        }

        // a:srgbClr
        $objWriter->startElement('a:srgbClr');
        $objWriter->writeAttribute('val', $color->getRGB());

        // a:alpha
        $objWriter->startElement('a:alpha');
        **if(!is_null($alpha)) 
            $alpha = 100;**

        $objWriter->writeAttribute('val', $alpha * 1000);
        $objWriter->endElement();

        $objWriter->endElement();
    }
```
##

**Comment by Progi1984** [comment]
@slewitan It's not a solution that you brings here.

You override ```$alpha``` if it is defined.
You should define the alpha value in your ```->setColor()``` use.

**Comment by slewitan** [comment]
@Progi1984,
I don't see how to set alpha in setColor it only excepts a color

    public function setColor(StyleColor $color = null)
    {
        $this->color = $color;
        return $this;
    }

can you please explain?

**Comment by Progi1984** [comment]
@slewitan You can define your color in ARGB (Alpha Red Green Blue) mode.

https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Style/Color.php#L80

**Comment by slewitan** [comment]
@Progi1984,
Thank you will look in to it.

**Comment by Progi1984** [comment]
@slewitan Perfect :)
