### ISSUE TITLE
Class 'PhpOffice\Common\XMLWriter' not found

### ISSUE THREAD

**Issue by SlowBus** [PHPOffice/PHPPresentation#235]

**Comment by danielbair** [comment]
I'm getting the same thing here when trying to run the samples...

Sample 01 Simple
18:09:15 Create new PHPPresentation object
18:09:15 Set properties
18:09:15 Create slide
18:09:15 Create a shape (drawing)
18:09:15 Create a shape (rich text)
Fatal error: Class 'PhpOffice\Common\XMLWriter' not found in PHPPresentation-0.6.0/src/PhpPresentation/Writer/PowerPoint2007/AbstractPart.php on line 74

**Comment by danielbair** [comment]
The issue was from not using composer and downloading the release manually. The installation instructions did not mention the need for PHPOffice/Common. I have created a pull request here... https://github.com/PHPOffice/PHPPresentation/pull/254

**Comment by Progi1984** [comment]
Fixed in the commit dbc34df.
