### ISSUE TITLE
Getting externalSlide with shape

### ISSUE THREAD

**Issue by disiri** [PHPOffice/PHPPresentation#240]
I am trying to get externalSlide from existing ppt file but somehow the table/shape is not successfully copied. I am using addExternalSlide/addSlide method. This method [#143](https://github.com/PHPOffice/PHPPresentation/issues/143) works perfectly on other content of text and styles of text as well as the images in the slides. Do I need to add some code in order to get the shape from externalSlide?

Thank you!

**Comment by Progi1984** [comment]
Added to the milestone 0.8

**Comment by Progi1984** [comment]
PR : #335

**Comment by Progi1984** [comment]
Merged in develop branch.
