### ISSUE TITLE
PHP Presentation Reading Text

### ISSUE THREAD

**Issue by 007manu007** [PHPOffice/PHPPresentation#242]
I want to read text of ppt not other info, so how I can do it with PHPPresenation?

Currently I get Tree Structure, I don't want tree structure I only want text
##

**Comment by MariaGabriel108** [comment]
Hello! Can you help me with my problem?
I'm trying to use the reader but i get this fatal problem:

 Uncaught exception 'Exception' with message 'File ./resources/phppowerpoint_logo.gif not found!' in C:\xampp\PHPPresentation-master\src\PhpPresentation\Shape\Drawing.php:107 Stack trace: #0 C:\xampp\PHPPresentation-master\samples\Sample_Header.php(49): PhpOffice\PhpPresentation\Shape\Drawing->setPath('./resources/php...') #1 C:\xampp\htdocs\sanagumana.php(8): include_once('C:\\xampp\\PHPPre...') #2 {main} thrown in C:\xampp\PHPPresentation-master\src\PhpPresentation\Shape\Drawing.php on line 107

can you help me? plss?

**Comment by Progi1984** [comment]
@007manu007 You need to browse all the file... each slide... each shape ... and for each shape, make a toString() on the shape.
