### ISSUE TITLE
Fatal error File ./resources/phppowerpoint_logo.gif not found

### ISSUE THREAD

**Issue by MariaGabriel108** [PHPOffice/PHPPresentation#245]
I was in the process of viewing an existing pptx file using the reader of Powerpoint2007 but i get this fatal error:

Fatal error: Uncaught exception 'Exception' with message 'File ./resources/phppowerpoint_logo.gif not found!' in C:\xampp\PHPPresentation-master\src\PhpPresentation\Shape\Drawing.php:107 Stack trace: #0 C:\xampp\PHPPresentation-master\samples\Sample_Header.php(49): PhpOffice\PhpPresentation\Shape\Drawing->setPath('./resources/php...') #1 C:\xampp\htdocs\sanagumana.php(8): include_once('C:\xampp\PHPPre...') #2 {main} thrown in C:\xampp\PHPPresentation-master\src\PhpPresentation\Shape\Drawing.php on line 107

I already check the resources folder and phppowerpoint_logo.gif is there. What can I do??
##

**Comment by MariaGabriel108** [comment]
@Progi1984

**Comment by Progi1984** [comment]
@MariaGabriel108 Have you got always the problem with the develop branch ?

**Comment by Progi1984** [comment]
@MariaGabriel108 Have you got always the problem with the develop branch ?

**Comment by Progi1984** [comment]
@MariaGabriel108 PhpPresentation 0.8.0 has been released. I would like to solve your issue for 0.9.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@MariaGabriel108 PhpPresentation 0.9.0 has been released. I would like to solve your issue for 0.10.0. Could you answer to my question ?

**Comment by whitakerc18** [comment]
I'm having a similar issue, I get this error: "Fatal error: Uncaught exception 'Exception' with message 'File ./resources/phppowerpoint_logo.gif not found!", but the file does exist in that path.

**Comment by atm080203** [comment]
I'm have a same issue, just because the file don't have the right permission

**Comment by Progi1984** [comment]
Check rights problem before reading
