### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by RomanSyroeshko** [PHPOffice/PHPPresentation#25]
It seems that ```PowerPoint``` is a [registered trademark](http://www.microsoft.com/en-us/legal/IntellectualProperty/Trademarks/EN-US.aspx#P_Title) of Microsoft.

I suggest to rename into ```PHPPresentation```.

**Comment by Progi1984** [comment]
... WIP ...

**Comment by Progi1984** [comment]
... DONE...

A link to FAQ for explaining the change : http://phppowerpoint.readthedocs.org/en/develop/faq.html#why-phppowerpoint-become-phppresentation

ToDo Release : 
- [ ] After push to master, rename the repository
- [ ] Check ReadTheDocs @readthedocs
- [ ] Check Packagist @packagist
- [ ] Check Scrutinizer-CI @scrutinizer-ci
- [ ] Check Gitter @gitterHQ
- [ ] Check Documentation generation

**Comment by Progi1984** [comment]
New project RTD created

**Comment by Progi1984** [comment]
New project Scrutinizer CI created
