### ISSUE TITLE
Fatal error: Class 'PhpOffice\Common\Adapter\Zip\ZipArchiveAdapter' not found

### ISSUE THREAD

**Issue by danielbair** [PHPOffice/PHPPresentation#250]
Sample 01 Simple
18:18:42 Create new PHPPresentation object
18:18:42 Set properties
18:18:42 Create slide
18:18:42 Create a shape (drawing)
18:18:42 Create a shape (rich text)
Fatal error: Class 'PhpOffice\Common\Adapter\Zip\ZipArchiveAdapter' not found in PHPPresentation-develop/src/PhpPresentation/Writer/PowerPoint2007.php on line 77

**Comment by danielbair** [comment]
The issue was from not using composer and downloading the release manually. The installation instructions did not mention the need for PHPOffice/Common. I have created a pull request here... https://github.com/PHPOffice/PHPPresentation/pull/254

**Comment by Progi1984** [comment]
Fixed in the commit dbc34df.

**Comment by abhishek-swt** [comment]
Hello guys, I have manually downloaded PHPPresentation and facing the same problem.
I have downloaded the master branch from your repository. How can I fix this?
