### ISSUE TITLE
README.md missing requirements

### ISSUE THREAD

**Issue by danielbair** [PHPOffice/PHPPresentation#251]
The README.md does not mention the PHPOffice/Common as a requirement for PHPPresentation.
Thus if one is downloading PHPPresentation source and attempting to use the samples it will throw errors about PHPOffice/Common/... file not found.

**Comment by danielbair** [comment]
I have created a pull request here... https://github.com/PHPOffice/PHPPresentation/pull/254

**Comment by Progi1984** [comment]
Fixed in the commit dbc34df.

**Comment by Progi1984** [comment]
And documentation added : http://phppresentation.readthedocs.io/en/develop/installing.html
