### ISSUE TITLE
Format axis line

### ISSUE THREAD

**Issue by informed-source** [PHPOffice/PHPPresentation#255]
Is it possible to format the axis line for a chart in PHPPresentation? Our style requires that there is no visible Y axis line, only the labels.

**Comment by Progi1984** [comment]
@informed-source Which type of format do you want to apply to axis (x or y) ?

Note&nbsp;:&nbsp;https://github.com/PHPOffice/PHPPresentation/blob/def46846e02e5860d3fd34f1df769ffaf9c51b9d/src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php#L2089

**Comment by informed-source** [comment]
Thanks for the prompt response.
In our case we would like the equivalent of Format>Axis>Line>No Line in PowerPoint.
So something like:
getAxisY()->setLine([outline object])
similar to the implementation for Gridlines would work.

**Comment by Progi1984** [comment]
@informed-source Could you test the PR, please ?

**Comment by informed-source** [comment]
Thanks for looking at this. Currently experiencing an issue with 0.7 which I need to resolve.

**Comment by informed-source** [comment]
I am unable to get version 0.7 to generate valid PowerPoint files. I have rolled back to my earlier release. I tried updating only the following files:
PhpPresentation/Shape/Chart/Axis.php
PhpPresentation/Writer/PowerPoint2007/PptCharts.php
and I get an error:
PHP Fatal error:  Uncaught ReflectionException: Class PhpOffice\\PhpPresentation\\Writer\\PowerPoint2007\\PptCharts ... does not exist ...
thrown in
PhpOffice/PhpPresentation/Writer/PowerPoint2007.php on line 115
$o = new \ReflectionClass($class);

**Comment by Progi1984** [comment]
@informed-source The writer PowerPoint has changed between 0.6 & 0.7

**Comment by informed-source** [comment]
Understood. Version 0.7 does not produce valid PowerPoint files for me.

**Comment by Progi1984** [comment]
@informed-source Is it this ticket : #266 ?

**Comment by informed-source** [comment]
It may be related. My symptoms are that the output file is either unreadable by PowerPoint on my Mac, or it does not contain the intended content. This is a breaking change since 0.6.

**Comment by Progi1984** [comment]
@informed-source Could you test this PR #303 ? Please and thanks for advance

**Comment by Progi1984** [comment]
@informed-source The PR #303 has been merged in develop branch. Thanks.

**Comment by Progi1984** [comment]
@informed-source Could you test the PR #255 ? Please, I need to merge it :)

**Comment by informed-source** [comment]
Tested and working. Thanks.
It was not immediately obvious how to achieve the equivalent of PowerPoint Format>Axis>Line>No Line.
Tried
$oOutlineAxisY->getFill()->setFillType(Fill::FILL_NONE)
but that did not seem to work
Tried
$oOutlineAxisY->setWidth(0);
and that did not appear to work either.
Tried
$oOutlineAxisY->getFill()->getStartColor()->setRGB('FFFFFF');
Which works sets it to the same colour as my background, but is not exactly equivalent to NONE.

Any suggestions?

Also, I noticed that the Axis titles now appear to work, where they did not appear previously.
Is there a better way of suppressing them than
$shape->getPlotArea()->getAxisX()->setTitle('');
?

Thanks again for your continuing work on this.

**Comment by Progi1984** [comment]
@informed-source I just fixed the 

```php
$oOutlineAxisY->getFill()->setFillType(Fill::FILL_NONE);
```

For the moment, the only way is : 
```php
$shape->getPlotArea()->getAxisX()->setTitle('');
```

Could you test the PR #263 ? Please, I need to merge it :)

**Comment by informed-source** [comment]
Excellent. This now works for me:
`$oOutlineAxisY->getFill()->setFillType(Fill::FILL_NONE);`

Thanks again.

**Comment by Progi1984** [comment]
Merged in develop branch.

**Comment by youssefboudaya** [comment]
is it possible to change the label's color of the axis X and Y when using line chart ?

**Comment by Progi1984** [comment]
@youssefboudaya Please create a new issue.
