### ISSUE TITLE
legend borders

### ISSUE THREAD

**Issue by pgee70** [PHPOffice/PHPPresentation#265]
Hi
I can't see how to set the legend border of a charts legend
http://phpoffice.github.io/PHPPowerPoint/docs/develop/classes/PhpOffice.PhpPresentation.Shape.Chart.Legend.html#method_getBorder

There is a getter, but not a setter.
##

**Comment by Progi1984** [comment]
PR : #334

**Comment by Progi1984** [comment]
Merged in develop branch.
