### ISSUE TITLE
axis titles in sample 5 doesn't work.

### ISSUE THREAD

**Issue by pgee70** [PHPOffice/PHPPresentation#267]
Sorry for so many issues, but if you don't know about them, you don't know.

in Sample_05_Chart_with_PHPExcel.php
line 69,70:
$shape->getPlotArea()->getAxisX()->setTitle('Month');
$shape->getPlotArea()->getAxisY()->setTitle('Downloads');

do not appear to be working:

![image](https://cloud.githubusercontent.com/assets/5938974/18548914/96662028-7b8e-11e6-843d-5bf0765756db.png)
setting the axis title in powerpoint reveals the default text of 'Axis Title'
I did some tracing and the values appear to save in the local object,  they seem to be written with the  $objWriter->writeElement('a:t', $oAxis->getTitle()); in PhpOffice\PhpPresentation\Writer\PowerPoint2007\PptCharts
but after that I don't know what happens...
##

**Comment by pgee70** [comment]
i think i have a fix for this one:
in Powerpoint2007:PptCharts::writeAxis around line 2079 there is a missing c:title element (outdented)
```
      // c:tickLblPos
        $objWriter->startElement('c:tickLblPos');
        $objWriter->writeAttribute('val', 'nextTo');
        $objWriter->endElement();

        // c:txPr
$objWriter->startElement('c:title');
     
        $objWriter->startElement('c:txPr');

```
// this needs to be closed around line 2148
 // ## c:txPr
```
        $objWriter->endElement();
 
 $objWriter->endElement();   

```

**Comment by Progi1984** [comment]
@pgee70 I just modified your fix. Could you test the PR #288 ?

**Comment by Progi1984** [comment]
@pgee70 Some feedback, please.

**Comment by TuanTran07** [comment]
@Progi1984 Can you help me with this issue? Thanks.
https://github.com/PHPOffice/PHPPresentation/issues/298

**Comment by Progi1984** [comment]
@pgee70 Some feedback, please.

**Comment by pgee70** [comment]
Hi.  If the X and Y titles are now visible in Sample_05_Chart_with_PHPExcel  then call it fixed!

**Comment by Progi1984** [comment]
@pgee70 Fixed in develop branch
