### ISSUE TITLE
bar charts are not honouring the setLabelPosition

### ISSUE THREAD

**Issue by pgee70** [PHPOffice/PHPPresentation#268]
Hi, this one is easy!
the PhpOffice\PhpPresentation\Writer\PowerPoint2007\PptCharts.php::writeTypeBar does not honour series:setLabelPosition.

in line 982 adding:

``` php
$this->writeElementWithValAttribute($objWriter, 'c:dLblPos', $series->getLabelPosition());
```

seems to fix the issue (i just looked at the code for writeTypePie to see this.
##

**Comment by Progi1984** [comment]
@pgee70 Hi, Could you give me a screenshot with the bug ? Thanks.

**Comment by pgee70** [comment]
Thanks for responding.
It is not something taking a screenshot of can help. The code isn't implemented so the feature doesn't work.
The column label position just goes to the default position - I wanted it to go in the end of the label and it wouldn't work.

When that line is added the label position behaves as expected.

**Comment by Progi1984** [comment]
@pgee70 I just modified your fix. Could you test the PR #289 ?

**Comment by Progi1984** [comment]
@pgee70 Some feedback, please.

**Comment by Progi1984** [comment]
@pgee70 Some feedback, please.

**Comment by Progi1984** [comment]
@pgee70 Fixed in develop branch
