### ISSUE TITLE
Feature request: axis bounds

### ISSUE THREAD

**Issue by pgee70** [PHPOffice/PHPPresentation#269]
In scientific publishing we like to show the zero point on a graph as autoscaling can distort the difference between columns in a bar graph.
To do this can the min/max bounds of an axis be exposed to the library?
##

**Comment by Progi1984** [comment]
@pgee70 Hi, Could you give two screenshots : one with a sample and an another with the window in PowerPoint/LibreOffice for defining these options ? Thanks.

**Comment by pgee70** [comment]
Sure, thanks for looking at it.

[test.pptx](https://github.com/PHPOffice/PHPPresentation/files/477808/test.pptx)
![screenshot](https://cloud.githubusercontent.com/assets/5938974/18603558/049e0eac-7cb6-11e6-80fa-2002efe80177.png)
Note that in the attached presentation the column labels are above the column (in white colour).  See my issue #268  
Thanks

**Comment by Progi1984** [comment]
@pgee70 I don't find the option in PowerPoint2007. Do you know where it is ?

**Comment by Progi1984** [comment]
PR : #333

**Comment by Progi1984** [comment]
Merged in develop branch.
