### ISSUE TITLE
Line breaks in text labels of chart

### ISSUE THREAD

**Issue by idoraquel** [PHPOffice/PHPPresentation#271]
It might be not possible to choose rotation 0" but with auto line breaks.
I didn't find any method in Series. Am i right ?

Thanks
![screenshot from 2016-09-19 17-36-57](https://cloud.githubusercontent.com/assets/9630979/18635954/b56756e6-7e8f-11e6-942c-de61065dd08d.png)
![screenshot from 2016-09-19 17-36-26](https://cloud.githubusercontent.com/assets/9630979/18635953/b5398ab8-7e8f-11e6-9310-0f2698c30adf.png)
##

**Comment by maheshdama13** [comment]
I am also looking for the same, to change angle/rotation of X axis label. If you find it then let me know. Thanks in advance

**Comment by Progi1984** [comment]
Fixed in #410 (ODPresentation & PowerPoint2007 Writer) on develop branch (and will be available in 1.0.0 version).
