### ISSUE TITLE
Bug: show series values and name

### ISSUE THREAD

**Issue by Codealist** [PHPOffice/PHPPresentation#272]
It seems it doesn't matter either we set TRUE or FALSE to methods:

`Series::setShowValue();`
`Series::setShowSeriesName();`

It present by default even we set false

**Type**: ODP (Ubuntu 16.04) LibreOffice
##

**Comment by Progi1984** [comment]
Link to PR #332

**Comment by Progi1984** [comment]
Merged in develop branch.
