### ISSUE TITLE
Type graphics Area do not work

### ISSUE THREAD

**Issue by alejandrososa** [PHPOffice/PHPPresentation#275]
I am creating graphics and all have created fine except type graphics Area. I tried the example that comes in /vendor/phpoffice/phppresentation/samples/Sample_05_Chart.php bookstore and see that neither the presentation is added the area chart.

Whats not set any attributes to be added?
This is the code I'm testing:

``` php
    function fnSlide_Area(PhpPresentation $objPHPPresentation) {

    global $oFill;
    global $oShadow;

    // Generate sample data for chart
    echo date('H:i:s') . ' Generate sample data for chart' . EOL;
    $seriesData = array(
        'Monday' => 12,
        'Tuesday' => 15,
        'Wednesday' => 13,
        'Thursday' => 17,
        'Friday' => 14,
        'Saturday' => 9,
        'Sunday' => 7
    );

    // Create templated slide
    echo EOL . date('H:i:s') . ' Create templated slide' . EOL;
    $currentSlide = createTemplatedSlide($objPHPPresentation);

    // Create a line chart (that should be inserted in a shape)
    echo date('H:i:s') . ' Create a area chart (that should be inserted in a chart shape)' . EOL;
    $areaChart = new Area();
    $series = new Series('Downloads', $seriesData);
    $series->setShowSeriesName(true);
    $series->setShowValue(true);
    $series->getFill()->setStartColor(new Color('FF93A9CE'));
    $series->setLabelPosition(Series::LABEL_INSIDEEND);
    $areaChart->addSeries($series);

    // Create a shape (chart)
    echo date('H:i:s') . ' Create a shape (chart)' . EOL;
    $shape = $currentSlide->createChartShape();
    $shape->getTitle()->setVisible(false);
    $shape->setName('PHPPresentation Daily Downloads')->setResizeProportional(false)->setHeight(550)->setWidth(700)->setOffsetX(120)->setOffsetY(80);
    $shape->setShadow($oShadow);
    $shape->setFill($oFill);
    $shape->getBorder()->setLineStyle(Border::LINE_SINGLE);
    $shape->getTitle()->setText('PHPPresentation Daily Downloads');
    $shape->getTitle()->getFont()->setItalic(true);
    $shape->getPlotArea()->setType($areaChart);
    $shape->getView3D()->setRotationX(30);
    $shape->getView3D()->setPerspective(30);
    $shape->getLegend()->getBorder()->setLineStyle(Border::LINE_SINGLE);
    $shape->getLegend()->getFont()->setItalic(true);
}
```

A greeting
##

**Comment by Progi1984** [comment]
@alejandrososa Hi, I have no problem with the sample. Could you test with the develop branch ?

![image](https://cloud.githubusercontent.com/assets/1533248/23529545/52aad060-ff9e-11e6-85b9-b3be0b57f044.png)

**Comment by Progi1984** [comment]
@alejandrososa PhpPresentation 0.8.0 has been released. I would like to solve your issue for 0.9.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@alejandrososa PhpPresentation 0.9.0 has been released. I would like to solve your issue for 0.10.0. Could you answer to my question ?

**Comment by TrevorBradleyCDN** [comment]
I think I've just hit this same bug.

I'm attempting to load an existing PHP Presentation which has a LibreOffice "Area".  The source xml file of the slide in question looks like:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
       xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
       xmlns:p14="http://schemas.microsoft.com/office/powerpoint/2010/main"
       xmlns:p15="http://schemas.microsoft.com/office/powerpoint/2012/main"
       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">
    <p:cSld>
        <p:spTree>
            <p:nvGrpSpPr>
                <p:cNvPr id="1" name=""/>
                <p:cNvGrpSpPr/>
                <p:nvPr/>
            </p:nvGrpSpPr>
            <p:grpSpPr>
                <a:xfrm>
                    <a:off x="0" y="0"/>
                    <a:ext cx="0" cy="0"/>
                    <a:chOff x="0" y="0"/>
                    <a:chExt cx="0" cy="0"/>
                </a:xfrm>
            </p:grpSpPr>
            <p:sp>
                <p:nvSpPr>
                    <p:cNvPr id="82" name="CustomShape 1"></p:cNvPr>
                    <p:cNvSpPr/>
                    <p:nvPr/>
                </p:nvSpPr>
                <p:spPr>
                    <a:xfrm>
                        <a:off x="0" y="0"/>
                        <a:ext cx="9143640" cy="6858000"/>
                    </a:xfrm>
                    <a:prstGeom prst="rect">
                        <a:avLst></a:avLst>
                    </a:prstGeom>
                    <a:solidFill>
                        <a:srgbClr val="ff0000"/>
                    </a:solidFill>
                    <a:ln>
                        <a:noFill/>
                    </a:ln>
                </p:spPr>
                <p:style>
                    <a:lnRef idx="2">
                        <a:schemeClr val="accent1">
                            <a:shade val="50000"/>
                        </a:schemeClr>
                    </a:lnRef>
                    <a:fillRef idx="1">
                        <a:schemeClr val="accent1"/>
                    </a:fillRef>
                    <a:effectRef idx="0">
                        <a:schemeClr val="accent1"/>
                    </a:effectRef>
                    <a:fontRef idx="minor"/>
                </p:style>
            </p:sp>
        </p:spTree>
    </p:cSld>
    <p:transition spd="med">
        <p:fade/>
    </p:transition>
    <p:timing>
        <p:tnLst>
            <p:par>
                <p:cTn id="1" dur="indefinite" restart="never" nodeType="tmRoot">
                    <p:childTnLst>
                        <p:seq>
                            <p:cTn id="2" dur="indefinite" nodeType="mainSeq"></p:cTn>
                            <p:prevCondLst>
                                <p:cond delay="0" evt="onPrev">
                                    <p:tgtEl>
                                        <p:sldTgt/>
                                    </p:tgtEl>
                                </p:cond>
                            </p:prevCondLst>
                            <p:nextCondLst>
                                <p:cond delay="0" evt="onNext">
                                    <p:tgtEl>
                                        <p:sldTgt/>
                                    </p:tgtEl>
                                </p:cond>
                            </p:nextCondLst>
                        </p:seq>
                    </p:childTnLst>
                </p:cTn>
            </p:par>
        </p:tnLst>
    </p:timing>
</p:sld>`

This should generate a red (FF0000) field that takes up the entire slide.

When I run IOFactory to load pptx slides, all the graphics and text are imported correctly, but these Areas are entirely discarded.  When I load this particular slide, the object shows no shapes in it whatsoever.

This is with the current dev-master.

**Comment by TrevorBradleyCDN** [comment]
This isn't quite what @alejandrososa was talking about.  Let me see if I can write up a new issue to summarize my problem.

**Comment by Progi1984** [comment]
@TrevorBradleyCDN Please open a new issue :)
