### ISSUE TITLE
$oPHPPresentation->createSlide() causing corrupted file

### ISSUE THREAD

**Issue by kimubach** [PHPOffice/PHPPresentation#282]
Hello,

I'm reading a pptx file and adding some slides but it allways gets corrupted and powerpoint asks to repair it and it gets repaired successfully.

Even adding a blank slide it shows the error

I attach the corrupted file generated by PHPPresentation and the same file repaired by PowerPoint

What can i do to fix that?

Thanks a lot!

[pptfileREPAIRED.pptx](https://github.com/PHPOffice/PHPPresentation/files/529520/pptfileREPAIRED.pptx)
[pptfileERROR.pptx](https://github.com/PHPOffice/PHPPresentation/files/529521/pptfileERROR.pptx)
##

**Comment by kimubach** [comment]
Solved!

Answer found at slackoverflow:
http://stackoverflow.com/questions/39964949/phppresentation-file-with-2-slides-requires-repair


Copy the layout.

$objPHPPresentation = new PhpPresentation();
$oMasterSlide = $objPHPPresentation->getAllMasterSlides()[0];
$oSlideLayout = $oMasterSlide->getAllSlideLayouts()[0];

Then copy the layout to each new slide:

$currentSlide->setSlideLayout($oSlideLayout);

**Comment by Progi1984** [comment]
@kimubach Could you test this PR #303 ? Please and thanks for advance

**Comment by Progi1984** [comment]
@kimubach The PR #303 has been merged in develop branch. Thanks.
