### ISSUE TITLE
How to customize the color and linestyle of the axisX and axisY

### ISSUE THREAD

**Issue by ybstrong** [PHPOffice/PHPPresentation#292]
Hi, thank you for the great work! I have two questions:
1. How to customize the color and linestyle of the X-axis and Y-axis?
2.  How to display the tickMarks of the X-axis and Y-axis?

**Comment by ybstrong** [comment]
To  solve question 1,
first, I have added a 'Outline'(PhpOffice\PhpPresentation\Style\Outline) property to PhpOffice\PhpPresentation\Shape\Chart\Axis, and add get/set methods; then add some codes to function _construct, like this:
public function __construct($title = 'Axis Title')
    {
        $this->title = $title;
        $this->font  = new Font();
        $this->outline = new Outline();
        $fill=new Fill();
        $fill->setFillType(Fill::FILL_SOLID);
        $fill->setEndColor($fill->getStartColor());
        $this->outline->setFill($fill);
    }

second, in PhpOffice\PhpPresentation\Writer\PowerPoint2007\Pptcharts, insert following codes to function writeAxis() at line 2044:
// c:spPr
        $objWriter->startElement('c:spPr');
        // Outline
        $this->writeOutline($objWriter, $oAxis->getOutline());      
        // ##c:spPr
        $objWriter->endElement();


To solve question 2:
in function writeAxis() of PhpOffice\PhpPresentation\Writer\PowerPoint2007\Pptcharts, default value is 'none' ,change to 'out'/'in'/'cross'.
// c:majorTickMark: in out none cross
        $objWriter->startElement('c:majorTickMark');
        $objWriter->writeAttribute('val', 'out');
        $objWriter->endElement();

**Comment by Progi1984** [comment]
@ybstrong Ever pushed in the develop branch. Thanks for your share :)

**Comment by youssefboudaya** [comment]
is there a way to change the color of the  values of the axis X and Y ?
