### ISSUE TITLE
Cannot enlarge the size of the Bar3D's graph

### ISSUE THREAD

**Issue by ybstrong** [PHPOffice/PHPPresentation#293]
I have tested the function 'fnSlide_Bar3D'  in the 'sample_05_chart', it works well, but when I enlarged the size of  the plotarea, the size of the graph didn't change.
[bar3d.pptx](https://github.com/PHPOffice/PHPPresentation/files/587766/bar3d.pptx)

**Comment by ybstrong** [comment]
I found the value of  **'autoscale'** property in '**3-D Rotation**' is **_false_**, if set the value to _'true_', the problem above could be solved. But where and how to set the value to '_true_' in program?

**Comment by Progi1984** [comment]
PR #341

**Comment by Progi1984** [comment]
Merged in develop branch...

With its documentation : http://phppresentation.readthedocs.io/en/develop/shapes_chart.html#view3d
