### ISSUE TITLE
Is it possible to use a tab in text?

### ISSUE THREAD

**Issue by eL-Prova** [PHPOffice/PHPPresentation#309]
Hi all,

I use the method for formatting my text. Using the method createTextRun.
Is it possible to use a tab in my text? So i can format my text on 2 lines on same start location.

Kind regards

**Comment by eL-Prova** [comment]
bump

**Comment by Progi1984** [comment]
@eL-Prova Have you tried to concatenate a `chr(9)` ?

**Comment by eL-Prova** [comment]
Hi @Progi1984,

Yes, I tried with that like:

$textRun = $shape->createTextRun('Thank you for using &#9; PHPPresentation!');

Any other idea's?

**Comment by Progi1984** [comment]
@eL-Prova May be that ?

```php
$textRun = $shape->createTextRun('Thank you for using '.chr(9).'PHPPresentation!');
```

**Comment by eL-Prova** [comment]
Hi @Progi1984,

No it seems it wont correctly transform it so the char seems ignored :-(
Any other idea's? (Ps tested in both formats and opened in Office 2013)

**Comment by Progi1984** [comment]
@eL-Prova I will investigate later.

**Comment by Progi1984** [comment]
@eL-Prova I just done 

```php
$textRun = $shape->createTextRun('Thank you for using '.chr(9).'PHPPresentation!');
```

The tabulation is well present :
![image](https://user-images.githubusercontent.com/1533248/30210384-c0c921ee-949c-11e7-97a3-edba18fbec7a.png)
![image](https://user-images.githubusercontent.com/1533248/30210397-d456e8e0-949c-11e7-80f4-add0048939cd.png)

**Comment by eL-Prova** [comment]
@Progi1984 I use version  5.6.30, when I make multiple spaces, it will be reduced to one space instead of multiple. char(9) is convert to a space. Should I take a newer version? Or do I do something wrong?

**Comment by Progi1984** [comment]
@eL-Prova Which version 5.6.30 ?
