### ISSUE TITLE
Add custom document properties

### ISSUE THREAD

**Issue by alexdemers** [PHPOffice/PHPPresentation#313]
It is possible to add predefined document properties such as creator, category, company etc. but not custom document properties like PhpSpreadsheet and PhpWord does.

**Comment by Progi1984** [comment]
@alexdemers Thanks for the report. Added to the roadmap.

Some clues for a PR : 
* https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Document/Properties.php#L438
* https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Writer/Xlsx/ContentTypes.php#L92
* https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Writer/Xlsx/DocProps.php#L206
* https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Writer/Xlsx/Rels.php#L55

**Comment by Progi1984** [comment]
Fixed in #411
