### ISSUE TITLE
Special character from database

### ISSUE THREAD

**Issue by jvanoostrom** [PHPOffice/PHPPresentation#318]
Hello,

I have a Powerpoint-writer that grabs data from a database and dynamically fills the Powerpoint. This data is submitted via user forms elsewhere. The database encoding is utf8mb4. The problem is the following:

When there is a ë or ï or any of those characters in the database, it breaks the Powerpoint slide it should be displayed to. The information is stored and retrieved correctly to and from the database, but for some reason fails in the slide.

Interesting note, however, is that when I do NOT use a variable text run, (e.g. $text->getText()) but a hard-coded string with any of these characters (e.g. Tiësto), the error is not generated. Only when pulling from the database, the Powerpoint breaks, asking for repairs and displays an empty slide after repairs.

As far as I know, the XML is formatted using utf8, which should be compatible with my utf8mb4. Do you have any idea as to how to solve my issue?

Thanks in advance!

Jeffrey

**Comment by jvanoostrom** [comment]
Issue can be closed. I have been using `strtolower()` rather than `mb_strtolower()`.

**Comment by DeathError** [comment]
Good afternoon. A similar problem for Russian characters with version 5.3 of php, problem 5.6 is not observed

**Comment by DeathError** [comment]
current solution mb_internal_encoding("UTF-8");
