### ISSUE TITLE
Feature request: set showLegendKey for Pie Chart

### ISSUE THREAD

**Issue by nitrocode** [PHPOffice/PHPPresentation#319]
I'm trying to set the property `showLegendKey` and the API doesn't have that ability. 

I saved my PPTX in 2 locations, one with `Legend Key` checked and one without. Extracted both archives and found that `chart5.xml` differed. The following formatted snippet XML is the difference.

```xml
<c:dLblPos val="outEnd" />
<c:showLegendKey val="1" /> <!-- this is the only difference among the other settings -->
<c:showVal val="0" />
<c:showCatName val="0" />
<c:showSerName val="0" />
<c:showPercent val="1" />
<c:showBubbleSize val="0" />
<c:showLeaderLines val="0" />
```

How difficult would it be to add this? Or has is already been added?

**Comment by Progi1984** [comment]
PR : #336

**Comment by Progi1984** [comment]
Merged in develop branch.
