### ISSUE TITLE
Style / Color

### ISSUE THREAD

**Issue by santiyank** [PHPOffice/PHPPresentation#344]
When i use this : 

```
.......
$text = 'WELCOME'; 
$Color = '004B87';

$textRun = $shape->createTextRun ($text );
 $textRun->getFont ()->setBold ( $bold )->setSize ( $size )->setColor ( new Color ( $color ) );
```

I can't see `$text`  in the Slide.

The real problem is `new Color ( $color )`  ,  so i change the min range to get alfa( 6 )  to 8   in [PHPPresentation/src/PhpPresentation/Style/Color.php](https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Style/Color.php#L95)

```
public function getAlpha()
    {
        $alpha = 100;
        if (strlen($this->argb) >=  8) {
            $dec = hexdec(substr($this->argb, 0, 2));
            $alpha = number_format(($dec/255) * 100, 2);
        }
        return $alpha;
    }
```

Preview : 

```
public function getAlpha()
    {
        $alpha = 100;
        if (strlen($this->argb) >=  6) {
            $dec = hexdec(substr($this->argb, 0, 2));
            $alpha = number_format(($dec/255) * 100, 2);
        }
        return $alpha;
    }
```
Now works,  but i need to know if this really work or not.

sorry for my english.

Thanks.

**Comment by vtiertant** [comment]
Hello,

Look the Color construct, this is not hexadecimal but argb.
Add 'FF' in front off your color .

`$Color = 'FF004B87';` 

Sorry too for my english ;)

**Comment by santiyank** [comment]
**Oh, that's great. I didn't thought to change the color format, Thank you so much.**
