### ISSUE TITLE
Donut Chart

### ISSUE THREAD

**Issue by kw-pr** [PHPOffice/PHPPresentation#355]
I would like to make a donut chart. From the documentation it looks like there is not option for this in the [Pie chart](http://phpoffice.github.io/PHPPresentation/docs/master/classes/PhpOffice.PhpPresentation.Shape.Chart.Type.Pie.html). 

Did I miss it or can someone point me in the direction to add this option?

I guess I would need to have a look at src/PhpPowerpoint/Writer/PowerPoint2007/Chart.php and add  c:doughnutChart in writeTypePie()...

**Comment by Progi1984** [comment]
Fixed in develop branch.
