### ISSUE TITLE
Reduce thickness of bar in Bar Chart

### ISSUE THREAD

**Issue by maheshdama13** [PHPOffice/PHPPresentation#358]
Hi,
I want to reduce width of bars in Bar Chart.
PFA

**Original Output**
![original_bar](https://cloud.githubusercontent.com/assets/13948725/25857409/a6eb3fb0-34f6-11e7-91b2-9775f7b6aaad.png)

**Required Output**
![require_bar](https://cloud.githubusercontent.com/assets/13948725/25857408/a6e6ae78-34f6-11e7-8fb1-f2fb240c732c.png)

**Comment by Progi1984** [comment]
Fixed in develop branch :)
