### ISSUE TITLE
Update to allow color for transparent png images 

### ISSUE THREAD

**Issue by JewrassicPark** [PHPOffice/PHPPresentation#370]
Hey, 

I needed this for a project so I added it to my hacked up phppres but it's a small change so thought you might want to merge it. 

In the writeShapeDrawing function of Writer/PowerPoint2007/PptSlides.php

You can add 

 $this->writeFill($objWriter, $shape->getFill());

just before writeBorder

Same way as in writeShapeText (though that now appears to be in the abstract file).

**Comment by Progi1984** [comment]
@JewrassicPark Fixed in develop branch (Reader / Writer - ODPresentation & PowerPoint2007)
