### ISSUE TITLE
Images bigger than Slide

### ISSUE THREAD

**Issue by DiegoLoTre** [PHPOffice/PHPPresentation#380]
I'm creating the images slide dynamically getting the source from some DB, but the image's width and heigh isnt the same for everyone, so i wonder if is a way to reduce the image if is bigger than the slide, and in case of a smaller, put it in the center

**Comment by Progi1984** [comment]
@DiegoLoTre Have you tried to define setWidth & setHeight for images shape ?

**Comment by DiegoLoTre** [comment]
But i only want to affect the ones that are bigger, not all

**Comment by Progi1984** [comment]
@DiegoLoTre You can browse all shapes. You filter only ImageShape. If images are bigger than slide, you setWidth & setHeight for these Images shapes.

**Comment by parixit572** [comment]
@Progi1984 Hey, is this issue resolved? As I can not add larger image at center.

Here is my code:
`
$imageData = "data:image/jpeg;base64,".base64_encode(file_get_contents('http://localhost/tmp_uploads/1.jpg'));
        list($width, $height) = getimagesize('http://localhost/tmp_uploads/1.jpg');
        //$shape->setWidthAndHeight($width, $height);
        $shape->setName('PHPPresentation logo')
            ->setDescription('PHPPresentation logo')
            ->setData($imageData)
            ->setResizeProportional(true)            
            ->setHeight(200)
            //->setWidth($width)
            //->setWidthAndHeight(600, 400)
            ->setOffsetX(0)
            ->setOffsetY(0);
        $currentSlide->addShape($shape);
`

**Comment by Progi1984** [comment]
@parixit572 Could you open a new issue, please ?
