### ISSUE TITLE
resizing ppt files from 16:9 or any custom aspect ratio to 4:3 without distortion of text and images

### ISSUE THREAD

**Issue by figochenfei** [PHPOffice/PHPPresentation#383]
I have tons of ppt files with different aspect ratios, i wanted to convert all the files to 4:3(25.4x19.05cm) without distortion. How can i achieve this? Thanks in advance.

**Comment by AndreasBergmann** [comment]
Hello I´ve got the same issue, is there a way ?

**Comment by Progi1984** [comment]
@figochenfei @AndreasBergmann You can : 
- open your files with PhpPresentaion Reader
- change the documentlayout : DocumentLayout
- save files with PhpPresentaion Writer
