### ISSUE TITLE
How to browse pptx by PHPPresentation

### ISSUE THREAD

**Issue by qlzxmacheng** [PHPOffice/PHPPresentation#386]
I need browse pptx on the Google Browser ,  but I use Sample 12 Reader PowerPoint2007 , only look tree , I need  browse pptx and it can play animation in the pptx , can you help me ? Thinks

**Comment by Progi1984** [comment]
@qlzxmacheng What is the Google Browser ?

You want to view a presentation (pptx or odp) in a browser ?

**Comment by qlzxmacheng** [comment]
yes ,  I want to  view a ppt in a browser ,  such as ppt -> H5  ,  Can you help me ?my english is not good...

**Comment by qlzxmacheng** [comment]
@Progi1984  Thinks for you,  I want to view a ppt in a browser, such as ppt -> h5 in a brower, Can you help me?  my English is very bad......

**Comment by Progi1984** [comment]
@qlzxmacheng What is h5 ?

What is your preffered language (french, for me) ?

**Comment by qlzxmacheng** [comment]
@Progi1984 Sorry , I am Chinese,   H5 is  html5 ,  i would like to view a ppt in the browser,  Can you help me?

**Comment by Progi1984** [comment]
Duplicates #221

**Comment by qlzxmacheng** [comment]
thank you very much

**Comment by Progi1984** [comment]
Duplicate of #221

**Comment by qlzxmacheng** [comment]
Do you have a good method to solve this problem?

**Comment by Progi1984** [comment]
Yes, write a PR with a HTML Writer :) or wait for it :)

**Comment by qlzxmacheng** [comment]
thank you

**Comment by sotirelisc** [comment]
Are there any updates on this?

Thanks.
