### ISSUE TITLE
Question about multiple Master Slides or Layouts

### ISSUE THREAD

**Issue by forexgg** [PHPOffice/PHPPresentation#388]
I had a question which I searched for a long time, hope someone could help.

**How do you generate multiple Master Slides and apply to different slides? 
or can you generate multiple layouts and apply to different slides?** 

either of these will solve my current problem.
Right now, I could only generate one Master slides and apply to other slides across the board.

Do you have any code examples?

**Comment by MindlineAnalytics** [comment]
I have the same question. If anybody can help urgently

**Comment by mhasanshahid** [comment]
Works as follows :

////Master Slide 1
$oMasterSlide1 = $objPhpPowerPoint->getAllMasterSlides()[0];
$shape = $oMasterSlide1->createDrawingShape();

$shape->setName('PHPPresentation logo')
->setDescription('PHPPresentation logo')
->setPath('resources/abc1.png')
->setHeight(36)
->setOffsetX(10)
->setOffsetY(100);
$shape->getShadow()->setVisible(false)
->setDirection(45)
->setDistance(10);

////Master Slide 2
$oMasterSlide2 = $objPhpPowerPoint->getAllMasterSlides()[1];
$shape = $oMasterSlide2->createDrawingShape();

$shape->setName('PHPPresentation logo')
->setDescription('PHPPresentation logo')
->setPath('resources/abc2.png')
->setHeight(36)
->setOffsetX(260)
->setOffsetY(350);
$shape->getShadow()->setVisible(false)
->setDirection(45)
->setDistance(10);

Now Master 1 is always default, and to apply master 2 :

$oSlideLayout = $oMasterSlide2->createSlideLayout();

//Slide in which you want to apply Master 2
$slide = $objPhpPowerPoint->createSlide();
$slide->setSlideLayout($oSlideLayout);

**Comment by forexgg** [comment]
@mhasanshahid 


I appreciate your reponse. When I new an instance,


```
$objPhpPowerPoint = new PhpPresentation();

$oMasterSlide1 = $objPhpPowerPoint->getAllMasterSlides()[0];
```


This is fine. But I think there is **only one MasterSlide generated**.

So when I tried this,

`
$oMasterSlide2 = $objPhpPowerPoint->getAllMasterSlides()[1];
`

It will give me an error "Undefined offset: 1", that is why I can't generate the second Master Slide.

Any thoughts?

**Comment by forexgg** [comment]
@mhasanshahid 

By adding

`
        $objPhpPowerPoint->createMasterSlide();
`

before 

`
$oMasterSlide2 = $objPhpPowerPoint->getAllMasterSlides()[1];
`

I was able to generate the second MasterSlide.  Will dig into more ...

Thanks!

**Comment by mhasanshahid** [comment]
@forexgg you got it exactly right.. 👍

**Comment by surajjdhv** [comment]
This helped me a lot. Thank you. A huge thanks to @Progi1984 for maintaining.
