### ISSUE TITLE
Can you help me how to get background in the ppt??

### ISSUE THREAD

**Issue by IkarosMa** [PHPOffice/PHPPresentation#393]
![image](https://user-images.githubusercontent.com/28077421/29021885-a9454352-7b99-11e7-963a-0ffa36d17896.png)
![image](https://user-images.githubusercontent.com/28077421/29021904-b4e4ace8-7b99-11e7-8416-89d81f5d0438.png)
![image](https://user-images.githubusercontent.com/28077421/29021912-c6b99a14-7b99-11e7-9b10-8a749893ae1b.png)
![tim 20170807180006](https://user-images.githubusercontent.com/28077421/29022044-4c9cdc18-7b9a-11e7-9aa8-37e3468b7fda.png)

in the ppt, this background is black,but I can't get this background,  can you help me??

**Comment by Progi1984** [comment]
Could you share the file, please ?

**Comment by IkarosMa** [comment]
[ccc.pptx](https://github.com/PHPOffice/PHPPresentation/files/1207040/ccc.pptx)

**Comment by IkarosMa** [comment]
who can help me save this problem?thank you.

**Comment by IkarosMa** [comment]
this is PHPPresentation's xml  
![image](https://user-images.githubusercontent.com/28077421/29102354-16b8b8a4-7ceb-11e7-813e-42479b2d6e90.png)
this is ppt's xml    
![image](https://user-images.githubusercontent.com/28077421/29102362-254b726c-7ceb-11e7-9365-1aa5abad2a97.png)

**Comment by IkarosMa** [comment]
my ppt is powerpoint 2016,  Do I must to use PowerPoint2007?

**Comment by Progi1984** [comment]
@IkarosMa Hi, PhpPresentation is a side project. I work on it on my free time.

**Comment by IkarosMa** [comment]
think you very much . I'll find another way in the Google ...

**Comment by Progi1984** [comment]
Duplicate the #397 :)
