### ISSUE TITLE
How can i get color by schemeClr?

### ISSUE THREAD

**Issue by IkarosMa** [PHPOffice/PHPPresentation#397]
![image](https://user-images.githubusercontent.com/28077421/29207524-1159098e-7eb9-11e7-877c-9aba13a939cc.png)
in the slide1, i get a color by schemeClr , is's val is accent1  ,  accent1 in the theme.xml,how can i get rgb color by schemeclr?

**Comment by Progi1984** [comment]
@IkarosMa Could you test the PR #401 ?

After that, you could read the color like this : `$oSlide->getBackground()->getSchemeColor()->getRGB()`

**Comment by Progi1984** [comment]
@IkarosMa Some news ?

**Comment by Progi1984** [comment]
@IkarosMa Some news ?

**Comment by Progi1984** [comment]
@IkarosMa Fixed in develop branch.
