### ISSUE TITLE
Memory limity end 300 slides

### ISSUE THREAD

**Issue by danielpromo** [PHPOffice/PHPPresentation#399]
Personal, I have a server with 4gb of ram, two cpus but I can not generate presentation with more than 50 mb, or 300 slides, I have 5000 slides.
Does anyone have a solution?

**Comment by juliohds** [comment]
split the slides, and after you can join. Or use a virtual machine

**Comment by pgee70** [comment]
if you have 5000 slides you are doing something wrong. 
No one is going to go to a presentation with 5000 slides, so consider what you want to really do.  would a standard PDF be a better output format?

**Comment by Progi1984** [comment]
@danielpromo Actually, I have no solution for that. But I will follow the answer of @pgee70 .
