### ISSUE TITLE
Exception - Array to string conversion

### ISSUE THREAD

**Issue by kkatadp** [PHPOffice/PHPPresentation#403]
https://github.com/PHPOffice/PHPPresentation/blob/097d50a7bf03bcdaec865dce1a46123bf01e5ddb/src/PhpPresentation/Writer/PowerPoint2007/LayoutPack/AbstractLayoutPack.php#L61

Said line causes an _Array to string conversion Exception_ in Laragon 3.1.2 w/ PHP 7.1.7. According to the doc comment, it should be an array, and changing it to `protected $themes = array();` does indeed fix the exception problem for me.

**Comment by Progi1984** [comment]
Fixed in develop branch (e5ef770fc1054d582a902de52940f64d42153418).
