### ISSUE TITLE
Editing an existing powerpoint file with PHPPresentation

### ISSUE THREAD

**Issue by bomg66** [PHPOffice/PHPPresentation#418]
I need to edit a powerpoint file. I've searched high and low all over the internet and I havent found anything. Please help!

**Comment by Progi1984** [comment]
@bomg66 Is it a PowerPoint97 or PowerPoint2007 file ?

**Comment by bomg66** [comment]
@Progi1984 PowerPoint2007

**Comment by Progi1984** [comment]
@bomg66 You have some samples here: 

https://github.com/PHPOffice/PHPPresentation/blob/develop/samples/Sample_12_Reader_PowerPoint2007.php
