### ISSUE TITLE
how to view ppt file in web like office365?

### ISSUE THREAD

**Issue by marin1993** [PHPOffice/PHPPresentation#423]
hello, I want to use it like this
[https://products.office.com/en-us/office-online/view-office-documents-online](url)
or like a pdf file view in chrome.
Products have no this function? what should I do?
Hope you can get your help, thank you!

**Comment by Progi1984** [comment]
@marin1993 It's a HTML Renderer.

Sample : https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fgithub.com%2FPHPOffice%2FPHPPresentation%2Fblob%2Fdevelop%2Fsamples%2Fresources%2FSample_12.pptx%3Fraw%3Dtrue

Duplicate #221
