### ISSUE TITLE
Fatal error on sample

### ISSUE THREAD

**Issue by phakn911** [PHPOffice/PHPPresentation#425]
Hello,
I have the following error message when i launch sample : 
Fatal error: Can't use method return value in write context in D:\web\xampp\htdocs\PHPPresentation\samples\Sample_Header.php on line 269

Do you have an idea.
Thanks.
Miky

**Comment by Progi1984** [comment]
Fixed in develop branch

**Comment by Progi1984** [comment]
Thanks @pgee70
