### ISSUE TITLE
通过Sample_12_Reader_PowerPoint2007.php文件读取文件，不做任何操作，再次导出PPT格式错误

### ISSUE THREAD

**Issue by bjxiaoxiao** [PHPOffice/PHPPresentation#426]
以下是简单的代码
$pptReader = IOFactory::createReader('PowerPoint2007');
$oPHPPresentation = $pptReader->load('resources/test001.pptx');

echo write($oPHPPresentation, basename(__FILE__, '.php'), $writers);

有什么办法可以使格式不变，原样呈现？

**Comment by Progi1984** [comment]
@bjxiaoxiao Sorry : could you translate your message in english ?

**Comment by phpsb** [comment]
你的意思是ppt样式出错吗?
