### ISSUE TITLE
Compress PPTX file size

### ISSUE THREAD

**Issue by parixit572** [PHPOffice/PHPPresentation#439]
Hello all,

I m creating PPTX with avg 20 images in each file and file size is near about 16/17 MB. I am already compressing image via PHP to reduce it's size in all possible manner.

However when I compress file manually using  https://www.wecompress.com/ then file is redeced to 2/3 MB! That is too much difference.

Can you please direct me to compress PPTX file further?

Thanks

**Comment by Progi1984** [comment]
@parixit572 Could you give us two samples (uncompressed & compressed) for understanding tips for compressing ?

**Comment by parixit572** [comment]
[ORIGINAL.pptx](https://github.com/PHPOffice/PHPPresentation/files/1611973/ORIGINAL.pptx)
[COMPRESSED.pptx](https://github.com/PHPOffice/PHPPresentation/files/1611974/COMPRESSED.pptx)

@Progi1984 Thank you for reply. I am attaching files as requested.

**Comment by Progi1984** [comment]
All the optimization is done on images (png => jpg) : 

![image](https://user-images.githubusercontent.com/1533248/34679371-06eb445a-f496-11e7-8d4a-9bbc4f80c995.png)

**Comment by Progi1984** [comment]
@parixit572 So you can do it oustide PhpPresentation :)
