### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by chriskapp** [PHPOffice/PHPPresentation#447]
Hi, we are currently using this library in a project where we need to generate a Doughnut chart. But unfortunately it is only available in the master and the latest 0.9 release does not include those classes. 
I saw the issue #378 where you list all todos for the 0.10 release. Do you want to implement all pending [milestones](https://github.com/PHPOffice/PHPPresentation/milestone/11) before you tag the next release or could you maybe move those to the next 0.11 version? This is also interesting for @sidler.

**Comment by Progi1984** [comment]
@chriskapp I would like to implement all current pull request before releasing 0.10.

**Comment by Progi1984** [comment]
@chriskapp I would like to implement all current pull request before releasing 0.10.

But currently, I have no time... I thought to have a patreon to finance some time to open source but I didn't know if people would be interested.
