### ISSUE TITLE
text direction control for Right-To-Left paragraphs

### ISSUE THREAD

**Issue by amirakbari** [PHPOffice/PHPPresentation#459]
there is no way to control Text Direction for RTLs Paragraphs

**Comment by amirakbari** [comment]
is there any way for set paragraphs to RTL (Right to Left) after 2 years  ?

**Comment by Progi1984** [comment]
@amirakbari Hi, Could you send me a sample file with the implemented feature, please, for implementation ?

**Comment by amirakbari** [comment]
@Progi1984 
please check https://github.com/PHPOffice/PHPPresentation/pull/657/commits

**Comment by Progi1984** [comment]
Cool. I have Fixed it 🤣
