### ISSUE TITLE
Who can give commercial support?

### ISSUE THREAD

**Issue by geri777** [PHPOffice/PHPPresentation#463]
Hi PHPOffice specialists! I would like to use PHPPresentation for a project, where I create a Powerpoint (pptx). This PPT will also include a third party plugin. I am looking for someone who has good experience with PHPPresentation and who can take over critical parts of this project. Feedback until end of March 2018, please. Please write to ranner(at)gmx.net or answer here. Thanks

**Comment by geri777** [comment]
I have not received any answers so far :-(

**Comment by Progi1984** [comment]
@geri777 Sorry, I have no time since the start of the year... I thought to have a patreon to finance some time to open source but I didn't know if people would be interested.
