### ISSUE TITLE
Design broken after add new slid on exiting ppt file

### ISSUE THREAD

**Issue by raghavzwt06** [PHPOffice/PHPPresentation#466]
I'm having issues when load ppt file and add new slide on that file and save result should not same as original ppt file.

Here attached both files 1) Original file: original.pptx
[original.pptx](https://github.com/PHPOffice/PHPPresentation/files/1872047/original.pptx)
 2) Generated file: generated.pptx 
[generated.pptx](https://github.com/PHPOffice/PHPPresentation/files/1872053/generated.pptx)

Please help me.

**Comment by Progi1984** [comment]
@raghavzwt06 Could you have the code for testing it on original.pptx ?
