### ISSUE TITLE
Open generated pptx file throw error when opening

### ISSUE THREAD

**Issue by newhope** [PHPOffice/PHPPresentation#47]
Hi, 

My server passed on the requirement checks 
(phpinfo: http://app.dbhost.in/nfo.php)

But after running your sample script, the generated pptx throw error when opening :

"PowerPoint found a problem with content in Sample_01_Simple.pptx. 
PowerPoint can attempt to repair the presentation.
If you trust the source of this presentation, click Repair."

I have attached the generated sample 1,2 for your easy investigating.
https://app.box.com/s/gyb0nc38zhkch7gz327k
Or you can view the direct link here:
http://app.dbhost.in/tmp/PHPPowerPoint/samples/

Please take a look

Thanks,
Minh

**Comment by shefik** [comment]
I am using version 0.4.0, and I am experiencing this error only on Chrome. It works fine Safari (Mac). The fixes outlined above are already applied in version 0.4.0, and the problem still persists.

**Comment by Progi1984** [comment]
@shefik Have you seen all patches in the bug ?
