### ISSUE TITLE
How can i display category name on x axis in group bar chart

### ISSUE THREAD

**Issue by mhasanshahid** [PHPOffice/PHPPresentation#499]
Like we display axis title, how can i display name of category on my x axis group bar chart?

**Comment by mhasanshahid** [comment]
@Progi1984

**Comment by mhasanshahid** [comment]
![category](https://user-images.githubusercontent.com/16210347/45089788-9c504e80-b10d-11e8-8253-c4d44e86fd69.png)

**Comment by mhasanshahid** [comment]
I am not able to see these kategorie names in my chart. Anyone can help me ?

**Comment by phpsb** [comment]
x name is Document array $seriesData1 key.

eg:
$seriesData1 = ['x-name-1'=>1,'x-name-2'=>2];

x-name-1 is x nama 
x-name-2 is x name

you know?

@mhasanshahid

**Comment by mhasanshahid** [comment]
Please read my question again.

**Comment by phpsb** [comment]
sorry ~ 

how do you know set header and footer ?

i dot find it

@mhasanshahid
