### ISSUE TITLE
how to set page header, foot in slides ? 

### ISSUE THREAD

**Issue by phpsb** [PHPOffice/PHPPresentation#500]
i need set page header, foot.

but ,i don't find document about it.

anybody can help me?

thanks.

**Comment by mhasanshahid** [comment]
There is a file named "Sample_Header". You can add that first, and see how its behaving.

**Comment by phpsb** [comment]
first, thanks your Reply.

yes, i can see 'Sample_Header' file.

but. don't find how to set slides header,foot.

@mhasanshahid

**Comment by mhasanshahid** [comment]
I have tested it by including it on top ...
include_once 'vendor/phpoffice/phppresentation/samples/Sample_Header.php';

and it works for me
