### ISSUE TITLE
Scatter chart Problem

### ISSUE THREAD

**Issue by mhasanshahid** [PHPOffice/PHPPresentation#501]
Scatter chart plot values from an array like (x=>y) so x is supposed to be a key and y is a value. But what if my x value repeats ? but in an array x is a key that can only exist once.

**Comment by mhasanshahid** [comment]
@Progi1984 How can i work with this problem?

**Comment by phpsb** [comment]
hi~
can you help me?

i hava a question,

but, i don't know how to say.

can you give me your email ?
thx 
@mhasanshahid

**Comment by mhasanshahid** [comment]
@phpsb you can write me here as you will write me on email.

**Comment by phpsb** [comment]
@mhasanshahid  

it's ok update file

you see top image 

i need move to bottom!

thanks man

**Comment by mhasanshahid** [comment]
@phpsb use $shape->getLegend()->setPosition(OPTIONS);

OPTIONS are : 
 const POSITION_BOTTOM = 'b';
    const POSITION_LEFT = 'l';
    const POSITION_RIGHT = 'r';
    const POSITION_TOP = 't';
    const POSITION_TOPRIGHT = 'tr';

Let me know if that helps.

**Comment by mhasanshahid** [comment]
@phpsb use POSITION_BOTTOM as  'b';

**Comment by phpsb** [comment]
@mhasanshahid 

ok~ thank you very much.

happy to you.
