### ISSUE TITLE
hi~ i need you help.

### ISSUE THREAD

**Issue by 3masterplus** [PHPOffice/PHPPresentation#503]
hi~

i before username is phpsb .

We have exchanged

now, i hava two question need you help.

if you know, please help me thx.

question 1:

Charts Y axis how to set percentage. like 10% 15% 26%

question 2:

my ppt is work, but i give other people, this ppt is error..

@mhasanshahid

**Comment by mhasanshahid** [comment]
@phpsb you mean  
$shape->getPlotArea()->getAxisY()->setMaxBounds( 100 );
this value you in %?

**Comment by mhasanshahid** [comment]
try this 
$shape->getPlotArea()->getAxisY()->setFormatCode('0%');

**Comment by phpsb** [comment]
DrawingShape  image path 

can use url ? 

i use url is error  file 'http://asdadasdad.com/abc.jpg' not found~

code
        $shape = $currentSlide->createDrawingShape();
        $shape->setPath('http://asdadasdad.com/abc.jpg')

is error.

eg: http://asdadasdad.com/abc.jpg

**Comment by mhasanshahid** [comment]
@phpsb did it worked correctly? or you did anything else?

**Comment by phpsb** [comment]
no no no..

Demand has changed.

so i dot make it.

hahha~

@mhasanshahid

**Comment by mhasanshahid** [comment]
@phpsb ok good luck

**Comment by phpsb** [comment]
i export ppt need Repair in office 2016

office 2013 Charts are broken 

what you use branch ? 

i use 0.9.0

wps is work, but office need Repair

do you meet that question ?

@mhasanshahid

**Comment by mhasanshahid** [comment]
@phpsb I dont understand your question. Please write english correctly or use a translator if you are from another language.

**Comment by phpsb** [comment]
when you open file(ppt), you meet powerpoints file is damage need repairing?

in powerpoints

@mhasanshahid
