### ISSUE TITLE
Migration from PHPExcel to PhpSpreadsheet

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPPresentation#504]
@mhasanshahid
> PHPPresentation  uses PHPExcel for writer of pptcharts, but at the same time the library  phpexcel itself says its depricated and should not be used, and  spreadsheet should be used. @Progi1984

**Comment by mhasanshahid** [comment]
@Progi1984 When will this update happen?in upcoming version 10 or?

**Comment by mhasanshahid** [comment]
@Progi1984 this migration should only be implemented under writer PptCharts or?

**Comment by mhasanshahid** [comment]
@Progi1984 Done with migration will give a pull request.

**Comment by Progi1984** [comment]
Fixed by #652
