### ISSUE TITLE
Sample_05_Chart.pptx need Repair

### ISSUE THREAD

**Issue by phpsb** [PHPOffice/PHPPresentation#505]
How to solve?

**Comment by phpsb** [comment]
open Sample_05_Chart.pptx in PowerPoint show need Repair.

Don't want to bother you, but i can't solve it.
 
@mhasanshahid 


anybody can solve it?

**Comment by mhasanshahid** [comment]
@phpsb Which office version are you using?

**Comment by mhasanshahid** [comment]
@phpsb Meanwhile can you also download my version of phppresentation, because for me all samples are working in my version.

**Comment by phpsb** [comment]
your mean is your : https://github.com/mhasanshahid/PHPPresentation ?

office 2016 and 2013.

**Comment by mhasanshahid** [comment]
@phpsb office 2016 it works perfect. Yes this one @phpsb

**Comment by phpsb** [comment]
@mhasanshahid  ok. thank you very much.

**Comment by mhasanshahid** [comment]
@phpsb is it working now with my version of it??

**Comment by phpsb** [comment]
@mhasanshahid  

no bro. my leader solve this question.

i feel composer install Library and https://phppresentation.readthedocs.io/en/latest/ Manual install Library is different.

fix PptCharts.php 102 line 

        $objWriter->writeElementIf($hPercent != null, 'c:hPercent', 'val', $hPercent . '%');
to
        $objWriter->writeElementIf($hPercent != null, 'c:hPercent', 'val', $hPercent);


i try your version, after complete my job.

thanks bro.

**Comment by mhasanshahid** [comment]
@phpsb delete all % signsss.... its an old fix that i have done way back.

**Comment by phpsb** [comment]
How about result？

Is't work now.

The day after tomorrow need online.  

So i don't hava enough time.

**Comment by Progi1984** [comment]
@phpsb @mhasanshahid Duplicates #382.
