### ISSUE TITLE
How to create charts with phppresentation ?

### ISSUE THREAD

**Issue by youssefboudaya** [PHPOffice/PHPPresentation#517]
I'm trying to create some charts i used the sample code in Sample_05_Chart.php.
this is my code:

      ` $objPhpPresentation = new PhpPresentation();

        $oFill = new Fill();
        $oFill->setFillType(Fill::FILL_SOLID)->setStartColor(new StyleColor('FFE06B20'));

        $oShadow = new Shadow();
        $oShadow->setVisible(true)->setDirection(45)->setDistance(10);
        $seriesData = array(
        'Monday' => 12,
        'Tuesday' => 15,
        'Wednesday' => 13,
        'Thursday' => 17,
        'Friday' => 14,
        'Saturday' => 9,
        'Sunday' => 7
        );

        $currentSlide = $objPhpPresentation->createSlide();

        // Create a line chart (that should be inserted in a shape)
        $lineChart = new Line();
        $series = new Series('Downloads', $seriesData);
        $series->setShowSeriesName(true);
        $series->setShowValue(true);
        $lineChart->addSeries($series);

        // Create a shape (chart)
        $shape = $currentSlide->createChartShape();
        $shape->setName('PHPPresentation Daily Downloads')->setResizeProportional(false)->setHeight(550)->setWidth(700)->setOffsetX(120)->setOffsetY(80);
        $shape->setShadow($oShadow);
        $shape->setFill($oFill);
        $shape->getBorder()->setLineStyle(Border::LINE_SINGLE);
        $shape->getTitle()->setText('PHPPresentation Daily Downloads');
        $shape->getTitle()->getFont()->setItalic(true);
        $shape->getPlotArea()->setType($lineChart);
        $shape->getView3D()->setRotationX(30);
        $shape->getView3D()->setPerspective(30);
        $shape->getLegend()->getBorder()->setLineStyle(Border::LINE_SINGLE);
        $shape->getLegend()->getFont()->setItalic(true);`
When i generate the file i get the repair error from my microsoft powerpoint 2013 is their a solution to this issue ?

**Comment by Progi1984** [comment]
@youssefboudaya Duplicates #382.
