### ISSUE TITLE
Doesnt work on PHP 5.3

### ISSUE THREAD

**Issue by lectronix** [PHPOffice/PHPPresentation#520]
Sample_Header.php line 283 uses empty() which doesn't work right on 5.3. Got around that but then got another exception 'Hoa needs at least PHP5.4 to work; you have 5.3.2-1ubuntu4.30.'

Gave up at that and seeing if my hosting co. will update PHP for me.

**Comment by Progi1984** [comment]
@lectronix It seems that the bug is not relative to PhpPresentation but to Hoa. (Hoa needs at least PHP5.4).
