### ISSUE TITLE
powerpoint detected unreadable content 

### ISSUE THREAD

**Issue by ridaajroudi** [PHPOffice/PHPPresentation#526]
currently i have a laravel project in which i need to generate a powerpoint document so i install phppresentation in cmd with the command
compose require phpoffice / phpresentation
the installation is going well so far there is no problem I used a simple code that I found in the documentation:
 $objPHPPowerPoint = new PhpPresentation();
$Slide1 = $objPHPPowerPoint->createSlide();
$shapeContent = $Slide1->createRichTextShape()
           ->setHeight(300)
           ->setWidth(700)
           ->setOffsetX(0)
           ->setOffsetY(100);

       $textParagraph = $shapeContent->createParagraph();
       $textParagraph->getFont()->setSize(14)->setColor(new Color( 'FF000000' ));

       $shapeContent->getActiveParagraph()->createTextRun("Test")->getFont()->setSize(14)->setColor( new Color( 'FF000000' ));
$shapeContent->getActiveParagraph()->getAlignment()->setHorizontal( Alignment::HORIZONTAL_RIGHT);
$oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');
       $oWriterPPTX->save(__DIR__ . "/sample.pptx");
       $oWriterODP = IOFactory::createWriter($objPHPPowerPoint, 'ODPresentation');
       $oWriterODP->save(__DIR__ . "/sample.odp");

the powerpoint file is generated but when i open it i get this  message  powerpoint detected unreadable content

**Comment by Progi1984** [comment]
@ridaajroudi Duplicates #382.
