### ISSUE TITLE
Dont work with Russian symbols

### ISSUE THREAD

**Issue by camper5510** [PHPOffice/PHPPresentation#533]
Hello. When i add text with russian symbols i got pptx file, but this file broken and need recovery. Any idea why its happening and how fix that?

**Comment by Progi1984** [comment]
@camper5510 Have you got a sample code for testing and fixing ?

**Comment by camper5510** [comment]
> Have you got a sample code for testing and fixing

I fixed that, it was problem with script file encoding.
