### ISSUE TITLE
Question: Is there any way to use .pot files with PHPPresentation?

### ISSUE THREAD

**Issue by CViniciusSDias** [PHPOffice/PHPPresentation#535]
I need to create presentations from a .pot (template) file. Can I use PHPOffice/PHPPresentation to do this?

**Comment by Progi1984** [comment]
Actually no... May be you can work a PR :) ?

**Comment by CViniciusSDias** [comment]
Oh... I actually don't even know what a .pot file is. I asked because one of the guys in the team brought it up. I'll try to study it.

**Comment by Progi1984** [comment]
Thanks. 🙏
