### ISSUE TITLE
Use phppresentation with php 5.6

### ISSUE THREAD

**Issue by denisgualda** [PHPOffice/PHPPresentation#538]
Hi,
totally newest with this library and low level with php obviously.
Any examples loads in my server.
It has php 5.6.... readme.md says you need ### Requirements PHP 5.3+

It's works with 5.6?

Regards and thanks!

**Comment by smithyj** [comment]
`index.php` write `require './vendor/autoload.php';`

**Comment by Progi1984** [comment]
PHP 5.3+ means  PHP > 5.3 
As you can see in travis build : https://travis-ci.org/PHPOffice/PHPPresentation/builds/543474880
