### ISSUE TITLE
Blank result from base64 image

### ISSUE THREAD

**Issue by Bagasdew** [PHPOffice/PHPPresentation#548]
I tried to add image from base64 code. And it gives me a blank slide with no image. I've tried all possible tutorial and it give me no result. Can somebody help?
Here is my code : 

```php
$oPhpPresentation = new PhpPresentation();
$oSlide = $oPhpPresentation->getActiveSlide();
$oShape = new Drawing\Base64();
$oShape->setData('data:image/jpeg;base64,(my base64 code)');
$oSlide->addShape($oShape);
$oWriterPPTX = IOFactory::createWriter($objPHPPowerPoint, 'PowerPoint2007');
$oWriterPPTX->save(__DIR__ . "/../../../../ppt/picture.pptx");
```

**Comment by Progi1984** [comment]
@Bagasdew Have you seen this sample ?

https://github.com/PHPOffice/PHPPresentation/blob/6a51e021404bb285ebdb2524e8143a434fea205b/samples/Sample_03_Image.php#L58-L68

**Comment by Bagasdew** [comment]
> 
> 
> @Bagasdew Have you seen this sample ?
> 
> https://github.com/PHPOffice/PHPPresentation/blob/6a51e021404bb285ebdb2524e8143a434fea205b/samples/Sample_03_Image.php#L58-L68

It's working! 😄 
But I still don't understand, what's wrong with my code. Can you explain? Thanks a lot

**Comment by Progi1984** [comment]
Just here, I think you don't define height and width

**Comment by Bagasdew** [comment]
thanks
