### ISSUE TITLE
OpenOffice and Charts

### ISSUE THREAD

**Issue by rdoepke** [PHPOffice/PHPPresentation#55]
Hi everyone,

I finally managed to get PHPExcel working with the latest version of PHPPowerPoint. When I run sample 8, the file opens correctly in PowerPoint it looks fine plus I can view and edit the chart. When I import it via OpenOffice (Version 3.4.1), the slides looks both different and the data is not attached.

![openoffice](https://cloud.githubusercontent.com/assets/2574570/4369785/e01d376a-4300-11e4-9220-ebe9d90b47c6.PNG)

BTW: Using the ODT writer the chart data exists. However, the diagram does not look like expected either.

Regards 
Roland
##

**Comment by Progi1984** [comment]
@rdoepke PHPPowerPoint 0.4.0 has been released. I would like to solve your issue for 0.5.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@rdoepke PHPPowerPoint 0.6.0 has been released. I would like to solve your issue for 0.7.0. Could you answer to my question ?

**Comment by rdoepke** [comment]
@Progi1984 Sorry haven't logged in to github for a while. I am no longer attached to the project in question and no longer have access to the codebase. Thus, I cannot test any more. Sorry about that.

**Comment by Progi1984** [comment]
@rdoepke Thank you for the feedback. I'll close the ticket.
