### ISSUE TITLE
Subscript and superscript

### ISSUE THREAD

**Issue by ianobre** [PHPOffice/PHPPresentation#573]
Hi there, its possible to create a text with subscript or superscript?

I need to write a simple text in my presentation: CO² 
but i dont know how can i do this.

Thanks in advanced,  Ismael

**Comment by 602303068** [comment]
$textRun->getFont()->setSuperScript(true);

**Comment by 602303068** [comment]
$textRun = $shape->createTextRun('CO');
$textRun = $shape->createTextRun('2');
$textRun->getFont()->setSuperScript(true);
