### ISSUE TITLE
tmp directory not configurable

### ISSUE THREAD

**Issue by nhalle** [PHPOffice/PHPPresentation#600]
Hi,

I was trying to rewrite the tmp directory so tmp files could be sent to my app's tmp directory, but tmp files are currently configured to be saved at the root './' `$pFilename = @tempnam('./', 'phppttmp')￼ `  [https://github.com/PHPOffice/PHPPresentation/blob/a352768c8c63722d877862e07fe8a27cf5fdffd2/src/PhpPresentation/Writer/ODPresentation.php#L8
](https://github.com/PHPOffice/PHPPresentation/blob/a352768c8c63722d877862e07fe8a27cf5fdffd2/src/PhpPresentation/Writer/ODPresentation.php#L8)

It seems that there is existing functionality to customize the `$this->diskCachingDirector￼` as the tmp directory [https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Writer/ODPresentation.php#L16](https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Writer/ODPresentation.php#L16)

Could we alternatively bring in this functionality and set `$pFilename = @tempnam($this->diskCachingDirector, 'phppttmp')￼ `?

**Comment by collectiveaccess** [comment]
We're having issues with this as well, where tmp files are being dumped into the app root and sometimes not cleaned up due to file permissions. It would be great to have the ability to route where these files land as it would make management of them so much simpler.
