### ISSUE TITLE
How can I get texts in ppt and pptx files.

### ISSUE THREAD

**Issue by BeycanDeveloper** [PHPOffice/PHPPresentation#619]
Hello, all I want is to get the texts in ppt and pptx files. I couldn't understand how I can do this. Can you help me?

I will send the ppt and pptx and assign the inside texts to a variable. How can I do?

**Comment by DionPotkamp** [comment]
Do something like this but just dont count the words:
```php
$presentation = IOFactory::createReader('PowerPoint2007')->load($pathToPresentation);
```
#620

**Comment by BeycanDeveloper** [comment]
Thank you
