### ISSUE TITLE
After setting the font, if it is Chinese, the set font has no effect

### ISSUE THREAD

**Issue by gaogan779322720** [PHPOffice/PHPPresentation#642]
For example, if I set Microsoft YaHei, it will not be Microsoft YaHei after export, but it is said in the upper left corner that it is Microsoft YaHei. In fact, it is not Microsoft YaHei font

**Comment by nicksenglish** [comment]
Almost two years later, I came across this same problem with Japanese characters. 

I solved it by setting the font format:
```
use PhpOffice\PhpPresentation\Style\Font;

$font = new Font();
$font->setName('ＭＳゴシック');
$font->setFormat(Font::FORMAT_EAST_ASIAN);
```
There are three options: FORMAT_LATIN, FORMAT_EAST_ASIAN and FORMAT_COMPLEX_SCRIPT.

They come from the PhpOffice\PhpPresentation\Style\Font class.
