### ISSUE TITLE
Line Chart Outline width being set to 0 no matter what

### ISSUE THREAD

**Issue by GisliNielsen** [PHPOffice/PHPPresentation#703]
Hello!

I am trying to set the color of my line chart and I found out that I need to use "Outline" for it to work. The color is being set correctly, but for some reason, the width of the lines in the line chart gets set to 0 pt (normally 2.25 pt). I thought that I was doing something wrong, but I tried your sample (samples/Sample_05_Chart_Line.php slide #2) and it also had the same issue. Any ideas to what is wrong here?

Correct line width (Without outline)
![image](https://user-images.githubusercontent.com/17725274/161017832-c6e03150-fd9f-435c-8823-835597699857.png)

Incorrect line width (With outline)
![image](https://user-images.githubusercontent.com/17725274/161017785-383348af-ea1f-4141-a3d3-8eaa234e2d98.png)

**Comment by GisliNielsen** [comment]
Found the issue! The problem is in the following file
AbstractDecoratorWriter.php
Inside the function writeOutline the width gets calculated based on CommonDrawing::pointsToEmu($width). This is the wrong unit conversion and needs to be adjusted. A bit unsure what the correct unit to use here, but if someone knows then I can create a PR with a fix for this issue.

**Comment by Pakku** [comment]
I've made a PR using pixelsToEmu instead of pointsToEmu, as it seems to work with that function.

**Comment by JackVanson** [comment]
Hi I have changed the AbstractDecoratorWriter.php to use pixelsToEmu but I'm still not seeing the width that I set in the PowerPoint. This is how I am setting the width. Am I doing something wrong?

        $staffOutline = new Outline();
        $staffOutline->getFill()->setFillType(Fill::FILL_SOLID);
        $staffOutline->getFill()->setStartColor(new Color($staff_col));
        $staffOutline->setWidth(5);

        $series2 = new Series("Staff", $staffScoreData);
        $series2->setOutline($staffOutline);
