### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by alfkoblischke** [PHPOffice/PHPPresentation#706]
I use PHP Presentation with Codeigniter 3. My vendor directory is under the application directory. I allwas get the Error-Message: Class 'ZipArchive' not found, as soon as I want to save a Presentation. It cant find: /vendor/phpoffice/common/src/Common/Adapter/Zip/ZipArchiveAdapter.php. But the file is there. Can anybody help?

**Comment by charleskennethhernandez** [comment]
Hello! Can I ask how did you implement the PHPPresentation Library to Codeigniter? Thanks

**Comment by charleskennethhernandez** [comment]
may i know how did you implement it via codeigniter?
