### ISSUE TITLE
PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore()

### ISSUE THREAD

**Issue by Bhadresh-Malankiya** [PHPOffice/PHPPresentation#729]
TypeError
PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given, called in /home/pc1/Expresstech/certificates_poc/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint2007.php on line 1129

![image](https://user-images.githubusercontent.com/64741307/212854437-992840bf-bbab-4f67-9681-cac7e217db5f.png)

using php 8.0 with laravel 8

I was struggling to solve this from last 1 day but at last I think this is some internal library files type error, please let me know solution or fix it asap.

**Comment by samverhoeven** [comment]
I can confirm this issue.
On [this ](https://github.com/PHPOffice/PHPPresentation/blob/732d029640b78b5010750949629f635ed984ee10/src/PhpPresentation/Reader/PowerPoint2007.php#L1129) line, the result of a division (will always be a float) is given to a function that expects an int.

**Comment by vibhavankhade** [comment]
I am facing same issue 
please help me out  
TypeError: PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given, called in D:\Projects\xampp8.2.4\htdocs\magento246p1\vendor\phpoffice\phppresentation\src\PhpPresentation\Reader\PowerPoint2007.php on line 1131 and defined in D:\Projects\xampp8.2.4\htdocs\magento246p1\vendor\phpoffice\phppresentation\src\PhpPresentation\Shape\RichText\Paragraph.php:367

**Comment by Progi1984** [comment]
@samverhoeven @Bhadresh-Malankiya @vibhavankhade Have you got a sample file with the error, please ?

**Comment by samverhoeven** [comment]
@Progi1984, I'm not sure anymore which files in my repos caused this issue, so that would that me too much time.
If the setSpacingBefore function really needs to receive an int, I would then cast the result of the division in PowerPoint2007 to an int. If the Paragraph can also work with the spacingBefore property being a float, I would just leave out the type hinting as long as php 7 is still supported.
Or am I oversimplifying things here?

**Comment by Progi1984** [comment]
@Bhadresh-Malankiya @samverhoeven @vibhavankhade This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).

**Comment by purohitvijay** [comment]
Hi @Progi1984 , 

Is it possible to address this issue in a patch, as it's a blocking problem? It would be helpful if the fix could be merged a bit sooner.

Thank You
