### ISSUE TITLE
TableDesign in PPHPowerPoint

### ISSUE THREAD

**Issue by chuebert** [PHPOffice/PHPPresentation#74]
It is possible to Style Tables like this:

Change border-color: white
https://dl.dropboxusercontent.com/u/6242507/PHPPowerpoint%20Example/Design_1.png

No border left, top and right
https://dl.dropboxusercontent.com/u/6242507/PHPPowerpoint%20Example/Design_2.pdf

**Comment by pranshuagrawal** [comment]
@Progi1984 any way by which I can completely get rid of borders from table?

**Comment by Progi1984** [comment]
@pranshuagrawal This method ?

```php
$cell->getBorders()->getLeft()->setLineWidth(0);
```
