### ISSUE TITLE
Presentations break with version 2309 of PowerPoint

### ISSUE THREAD

**Issue by jesseg-traqline** [PHPOffice/PHPPresentation#758]
With update version 2309 (Build 16827.20056 Click-to-Run) of Microsoft Office 365, any presentation that includes a chart object will show up as corrupted.  In some cases, any page containing a chart will be replaced with a blank slide.  In other cases, the presentation will fail to open completely.  

A coworker with an earlier version, 2307 (Build 16626.20170 Click-to-Run), reported that the presentations worked just fine, so I tried rolling back.  When I did, the presentations opened fine for me as well, with all slides and charts intact.  

Rolling back and pausing Microsoft Office updates may work as a temporary internal short term fix, but presentations made with PHPPresentation need to be compatible with the latest and future versions of Microsoft Office.

[MySandbox.pptx](https://github.com/PHPOffice/PHPPresentation/files/12673117/MySandbox.pptx)
I have created and attached a sample presentation that demonstrates the problem and contains no proprietary information:
- If opened with version 2309, slides 2 and 3 should show up as corrupt and be blanked.  Slides 1 and 4 should remain intact.
- If opened with version 2307 or earlier, all 4 slides should remain intact.

**Comment by Brenneisen** [comment]
@Progi1984 We have the same problem. Is there a way to get the error message from PowerPoint to understand where the problem is coming from? Is there a way to verify the XML output?

**Comment by Progi1984** [comment]
I understand that you are on the preview channel.

I check updates from Microsoft : https://learn.microsoft.com/en-us/officeupdates/current-channel-preview.
Nothing about charts/openxml in 2308 or 2309.

Like it's an insider program, we should wait next versions.

**Comment by Brenneisen** [comment]
For us, it is the current version 16.77 (23091001) under Mac (installed from the AppStore) and also the online version under Microsoft 365.

**Comment by Brenneisen** [comment]
@Progi1984 Do you have any ideas? The Mac version of PowerPoint is the current stable one. I don't know the version of the online PowerPoint version. But it used to work there, too, and now it doesn't. Pie charts seem to work, bar charts don't. Is there a way to get the error message from PowerPoint to understand where the problem is coming from?

**Comment by Progi1984** [comment]
Which version of PhpPresentation do you use ?

Could you send me a file who run well before and is broken now ?

**Comment by jesseg-traqline** [comment]
> Which version of PhpPresentation do you use ?
> 
> Could you send me a file who run well before and is broken now ?

Version 0.6.0.  This issue is affecting both newly generated files and files that were generated years ago.

The example file is linked in the OP.

**Comment by WFarmerEthisphere** [comment]
We are seeing the same issue as well, and we are using the latest version of PhpPresentation.

**Comment by Brenneisen** [comment]
Hi @Progi1984, we use the latest stable version of the framework (1.0). The current development version does not work too.

**Comment by WFarmerEthisphere** [comment]
You can better replicate this if you try to create a chart slide:

`      $shape = $slide->createChartShape();
        $shape->setName('Chart')
            ->setResizeProportional(false);
        $shape->getPlotArea()->setType($barChart);`

**Comment by ErikBernskiold** [comment]
Echoing this experience. Came here to troubleshoot why users of one of the applications we manage suddenly started reporting PowerPoints being broken. Using the latest dev version PHP Presentation.

Also confirming that the same problem exists for both new and old PowerPoints in this version.

Based on when volumes of reports started coming in, I'd suggest that it is Version 2309 (Build 16827.20130) that introduced this.

I'm no PowerPoint coding expert (I rather dislike the repair errors because they are so tedious to troubleshoot...) so not sure if there is a way to better find out what it doesn't like. But it does seem to be a bug in PPT. :(

**Comment by rappasoft** [comment]
Yeah, this is really putting a damper on my projects. We're trying to figure out a solution now. It's just slides with charts that are broken.

**Comment by ErikBernskiold** [comment]
Just switched to the beta track on Mac to confirm that the problem is still there in 16.79.23100109

**Comment by crs-snap** [comment]
Confirm that powerpoint Version 2309 Build 16.0.16827.20130 will not open pptx's with charts in them (at least bar charts) that have been generated with PHPPresentation.

**Comment by travhow99** [comment]
+1 same issue here on both Mac & Windows versions of PowerPoint with newly generated powerpoints and powerpoints > 1 year old, all with charts as @WFarmerEthisphere mentioned. Though mine won't even open now after attempting to repair it and Powerpoint says Powerpoint can't read the file.

**Comment by WFarmerEthisphere** [comment]
Here is a simple script to reproduce the issue:

```php
<?php

require_once 'vendor/autoload.php';

use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Shape\Chart\Type\Bar;
use PhpOffice\PhpPresentation\Shape\Chart\Series;
use PhpOffice\PhpPresentation\Shape\Chart\Title;

// Create a new presentation
$presentation = new PhpPresentation();

// Remove the default slide
$presentation->removeSlideByIndex(0);

// Create a new slide
$slide = $presentation->createSlide();

// Chart data
$seriesData = [
    'Category 1' => 1,
    'Category 2' => 4,
    'Category 3' => 3,
    'Category 4' => 2
];

// Create a bar chart
$barChart = new Bar();

$series = new Series('Sample Series', $seriesData);
$series->getFont()->setBold(true);

$barChart->addSeries($series);

// Add chart to slide
$shape = $slide->createChartShape();
$shape->setName('Simple Bar Chart')
    ->setResizeProportional(false)
    ->setWidth(600)
    ->setHeight(400)
    ->setOffsetX(100)
    ->setOffsetY(100);

$shape->getTitle()->setText('Basic Bar Chart');
$shape->getPlotArea()->setType($barChart);

// Save the presentation
$oWriterPPTX = IOFactory::createWriter($presentation, 'PowerPoint2007');
$oWriterPPTX->save("SimpleBarChartPresentation.pptx");

echo "Presentation created successfully!\n";
``` 

Run this locally, open SimpleBarChartPresentation in a MS Office version > 2309 and you'll see the error.

**Comment by ErikBernskiold** [comment]
Opening a presentation in LibreOffice and saving it back to a .pptx makes at least my broken presentations work again in PowerPoint...

However, opening the Powerpoint in Apple Keynote, the graphs are missing (although Keynote doesn't report it as broken). Although I don't know if that ever worked before...

**Comment by Scheissy** [comment]
looks like the axis have the wrong `formatCode` setting. the default value seems to be an empty string, but the value needs to be set to `General`.

i added the following 2 lines to the script provided by @WFarmerEthisphere:

```
$shape->getPlotArea()->getAxisX()->setFormatCode('General');
$shape->getPlotArea()->getAxisY()->setFormatCode('General');
```

needs confirmation if it works for all chart types or just the bar chart!!!

**Comment by ErikBernskiold** [comment]
Nice find @Scheissy! Confirming this works for bar, line and scatter.

**Comment by WFarmerEthisphere** [comment]
Just confirmed on my end that @Scheissy's fix works. Thanks!

**Comment by travhow99** [comment]
@Scheissy 's fix worked for me as well, thank you very much!

**Comment by WFarmerEthisphere** [comment]
PR created to fix this here:
https://github.com/PHPOffice/PHPPresentation/pull/761

**Comment by rasikkunwar** [comment]
Thanks for the solution. It fixed the issue. I was having issue with doughnut chart too. I put these lines of code, and it works for doughnut chart too.

So, this solution is working for line, area, bar and doughnut.

**Comment by ioguimaraes** [comment]
@Scheissy Nice shoot. My users app reported this bug last weekend, thanks for the solution!!!!

**Comment by mohamadt94** [comment]
@Scheissy  Wonderfull , works for me and solve my problem
