### ISSUE TITLE
Options for Charts

### ISSUE THREAD

**Issue by chuebert** [PHPOffice/PHPPresentation#76]
Hi,

it is possible to have charts like this:
![https://dl.dropboxusercontent.com/u/6242507/charts.png](https://dl.dropboxusercontent.com/u/6242507/charts.png)

In the left chart i want have the values on the left line and not by the points.
In the secon chart i want no paddings in the cake.

and it is possible to use percent by countet value or must i calculate it by my self?

**Comment by manikrds** [comment]
@Progi1984 Sorry for the same question.

Is Possible to have graph chart like this ??

![graph](https://cloud.githubusercontent.com/assets/10435483/5665094/e32f3f14-977b-11e4-9dd3-d0789fc503d4.jpg)

**Comment by Progi1984** [comment]
@manikrds At the moment, no.

You can have line charts but without filling zone under.

If you want implementation, create an issue for each feature which miss you in PHPPowerPoint.

**Comment by manikrds** [comment]
@Progi1984 

Can we set marker points in graph line ?

![markers_graph_line](https://cloud.githubusercontent.com/assets/10435483/5835743/1099bf9a-a192-11e4-9cd6-3e08f4b343b4.jpg)
