### ISSUE TITLE
Problem with instalation: phpoffice/phppresentation 1.0.0 requires phpoffice/phpspreadsheet ^1.9.0

### ISSUE THREAD

**Issue by Daniel-Pincay** [PHPOffice/PHPPresentation#790]
Hello, I would like to know if there is a way to install phpoffice/phppresentation when I have phpoffice/phpspreadsheet dev-master. I noticed that in these versions (develop and master respectively) there are many new functionalities. Thanks for answering.

**Comment by huelsgp27** [comment]
same problem.

**Comment by Progi1984** [comment]
Idea : Remove PhpSpreadSheet from dependencies.

And allow code to be functional with/without PhpSpreadSheet.

What do you think about that @Daniel-Pincay @huelsgp27 ?

**Comment by Progi1984** [comment]
@Daniel-Pincay @huelsgp27 This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
