### ISSUE TITLE
can not read PPTX

### ISSUE THREAD

**Issue by NiZerin** [PHPOffice/PHPPresentation#796]
```php
$ppt = \PhpOffice\PhpPresentation\IOFactory::load($pptPath);
```

```
PhpOffice\\PhpPresentation\\Reader\\PowerPoint2007::loadShapeRichText(): Argument #3 ($oSlide) must be of type PhpOffice\\PhpPresentation\\Slide\\AbstractSlide, PhpOffice\\PhpPresentation\\Slide\\Note given, called in /www/convert_center/vendor/phpoffice/phppresentation/src/PhpPresentation/Reader/PowerPoint2007.php on line 1375
```

**Comment by uziins** [comment]
Same issue, trying use another file, got this:
PhpOffice\PhpPresentation\Shape\RichText\Paragraph::setSpacingBefore(): Argument #1 ($spacingBefore) must be of type int, float given

**Comment by Progi1984** [comment]
@uziins @NiZerin Hi, Could you send me a sample file with error, please, for reproducing the bug ?

**Comment by uziins** [comment]
[test-template.pptx](https://github.com/user-attachments/files/16707444/test-template.pptx)

I just tried again with a blank slide, still error

**Comment by Progi1984** [comment]
@NiZerin @uziins This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).
