### ISSUE TITLE
new release needed

### ISSUE THREAD

**Issue by DanielRuf** [PHPOffice/PHPPresentation#812]
There are quite some changes and we would like to use phpspreadsheet v2. Currently this means composer goes to 0.2.0 or 0.9.0 but not 1.0.0 because of the `^1.9` SemVer version contraint.

For when is a new release scheduled and when can this be done?

https://github.com/PHPOffice/PHPPresentation/compare/1.0.0...develop

@Progi1984

**Comment by Progi1984** [comment]
@DanielRuf I think I will release the 1.1.0 version on the next week.

**Comment by Progi1984** [comment]
@DanielRuf The release is done.

**Comment by DanielRuf** [comment]
Thank you very much @Progi1984 =)

**Comment by Progi1984** [comment]
@DanielRuf This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).

**Comment by DanielRuf** [comment]
The composer file still has a version constraint, which prevents the usage of phpspreadsheet v2:

https://github.com/PHPOffice/PHPPresentation/blob/master/composer.json#L26

> we would like to use phpspreadsheet v2. Currently this means composer goes to 0.2.0 or 0.9.0 but not 1.0.0 because of the ^1.9 SemVer version contraint.

Do you know when v2 is supported via version constraint?

**Comment by Progi1984** [comment]
@DanielRuf This issue has been fixed by a maintainer. You can help him by sponsoring him through [Github sponsors](https://github.com/sponsors/Progi1984).

**Comment by DanielRuf** [comment]
Any details regarding the new release, that will contain these changes?

**Comment by DanielRuf** [comment]
@Progi1984 v3 probably also has to be added to the supported versions then, when it is released and tested / working with PhpPresentation: https://github.com/PHPOffice/PhpSpreadsheet/issues/3917#issuecomment-2343692083

**Comment by Progi1984** [comment]
@DanielRuf The next release will be there on the first  of October.
