### ISSUE TITLE
createTextRun empty generate errors on ppt

### ISSUE THREAD

**Issue by Gyzmoo** [PHPOffice/PHPPresentation#91]
Hi Progi,

I've worked on my generic ppt's exports. My customer is really satisfied.

However, i've found another issue on the engine.

If i create a RichTextShape empty, the file generated is corrupted.

EX:
$txt = "";
$textRun = $shape->createTextRun($txt );
or
$textRun = $shape->createTextRun(" ");

I would like to create myShape with fixed dimensions and AutoFit properties even if my data is empty. 

How can i do that ?

Thx for advance.

EDIT: I used develop-branches
##

**Comment by Progi1984** [comment]
@Gyzmoo Thanks for the bug report

Have you got a sample code for testing this ? Which writer do you use ?
I don't reproduce it.

May be the last version of the develop branch fix this issue. Could you test it ?

**Comment by Progi1984** [comment]
@Gyzmoo PHPPowerPoint 0.4.0 has been released. I would like to solve your issue for 0.5.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@Gyzmoo PHPPowerPoint 0.6.0 has been released. I would like to solve your issue for 0.7.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@Gyzmoo PhpPresentation 0.8.0 has been released. I would like to solve your issue for 0.9.0. Could you answer to my question ?

**Comment by Progi1984** [comment]
@Gyzmoo PhpPresentation 0.9.0 has been released. I would like to solve your issue for 0.10.0. Could you answer to my question ?

**Comment by rijvirajib** [comment]
Confirming - this 0.9.0 version fixes the empty text run crash.

**Comment by Progi1984** [comment]
@rijvirajib Thank you for the feedback :)
